---
title: "Untitled"
output: html_document
date: "2023-05-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(dplyr)
library(tidyr)
library(Hmisc)
library(jomo)
library(mice)
library(mitools)
library(rms)
library(mitml)
library(survminer)
library(patchwork) #Arrange plot
library(ggplot2)
library(GGally)
library(gridExtra)
library(png)
library(grid)
library(haven) #read_dta
```

```{r data}
data<-read_dta("PICC dynamic prediction v3.dta")

write.csv(data,"data.csv",row.names = F)  # need to be csv file, otherwise it fails
datanew<-read.csv("data.csv")  #import data again

#Update data: PCP66 is a male, baseline age is 74.8

datanew$sex[datanew$originalid=="PCP66"]<-0  #male is 0
datanew$agebl[datanew$originalid=="PCP66"]<-74.8

#update P150 H&Y year2 is 2 not 0
#update P757 H&Y year1 is 1.5 not 0

datanew$hyyr2[datanew$originalid=="P150"]<-2
datanew$hyyr1[datanew$originalid=="P757"]<-1.5

#UPDATE P195 need to be exclude cos patient decline the follow-up and without the visit date only mmse value in medical record

datanew<-datanew%>%
  filter(originalid!="P195")


```

```{r select variables need}


data1<-datanew%>%
  select("study","idpicc","originalid","incidencecase","agebl","sex","smoking","comorbiditylistbl","charlsonbl","updrsblpart1","updrsyr1part1","updrsyr2part1","updrsyr3part1","updrsyr4part1","updrsyr5part1","updrsyr6part1","updrsyr7part1","updrsyr8part1","updrsyr9part1","updrsyr10part1","mdsupdrspart3bltotalconvertedasa","mdsupdrspart3yr1totalconvertedas","mdsupdrspart3yr2totalconvertedas","mdsupdrspart3yr3totalconvertedas","mdsupdrspart3yr4totalconvertedas","mdsupdrspart3yr5totalconvertedas","mdsupdrspart3yr6totalconvertedas","mdsupdrspart3yr7totalconvertedas","mdsupdrspart3yr8totalconvertedas","mdsupdrspart3yr9totalconvertedas","mdsupdrspart3yr10totalconverteda","mdsupdrspart3yr11totalconverteda","mdsupdrspart3yr12totalconverteda","mmsebltotal","mmseyr1total","mmseyr2total","mmseyr3total","mmseyr4total","mmseyr4total","mmseyr5total","mmseyr6total","mmseyr7total","mmseyr8total","mmseyr9total","mmseyr10total","mmseyr11total","mmseyr11total","mmseyr12total","hybl","hyyr1","hyyr2","hyyr3","hyyr4","hyyr5","hyyr6","hyyr7","hyyr8","hyyr9","hyyr10","hyyr11","hyyr12","sebl","seyr1","seyr2","seyr3","seyr4","seyr5","seyr6","seyr7","seyr8","seyr9","seyr10","seyr11","seyr12","ledbl","ledyr1","ledyr2","ledyr3","ledyr4","ledyr5","ledyr6","ledyr7","ledyr8","ledyr9","ledyr10","ledyr11","ledyr12","ledyr13","ledyr14","ledyr15","datevisitbl","datevisityr1","datevisityr2","datevisityr3","datevisityr4","datevisityr5","datevisityr6","datevisityr7","datevisityr8","datevisityr9","datevisityr10","datevisityr11","datevisityr12","datevisityr13","datevisityr14","datevisityr15","datelastseen","datelastknownalive","datedeath","datedementia","datelost")

data1$study<-factor(data1$study,
                    levels = c(1,2,3,4,5,6),
                    labels= c("CamPalGN","ICICLE","NYPUM","ParkWest","PICNICS","PINE"))


#daily levodopa equivalent dose in ParkWest were all zero in baseline

data1[data1$study=="ParkWest",]$ledbl<-0

```

```{r check longitudinal outcome}

#---MMSE----

MMSE_data<-data1%>%
  select("study","idpicc","originalid","incidencecase","mmsebltotal","mmseyr1total","mmseyr2total","mmseyr3total","mmseyr4total","mmseyr4total","mmseyr5total","mmseyr6total","mmseyr7total","mmseyr8total","mmseyr9total","mmseyr10total","mmseyr11total","mmseyr11total","mmseyr12total")

MMSE_data%>%
  group_by(study)%>%
  count(is.na(mmsebltotal))

#All studies measured MMSE

#----S&E-----
  
SE_data<-data1%>%
  select("study","sebl","seyr1","seyr2","seyr3","seyr4","seyr5","seyr6","seyr7","seyr8","seyr9","seyr10","seyr11","seyr12")

SE_data%>%
  group_by(study)%>%
  count(is.na(sebl))

#S&E missing all in ICICLE

#----H&Y----

HY_data<-data1%>%
  select("study","idpicc","originalid","incidencecase","hybl","hyyr1","hyyr2","hyyr3","hyyr4","hyyr5","hyyr6","hyyr7","hyyr8","hyyr9","hyyr10","hyyr11","hyyr12")

HY_data%>%
  group_by(study)%>%
  count(is.na(hybl))

#All studies measured H&Y

#-----daily levodopa equivalent doses----

led_data<-data1%>%
  select("study","idpicc","originalid","incidencecase","ledbl","ledyr1","ledyr2","ledyr3","ledyr4","ledyr5","ledyr6","ledyr7","ledyr8","ledyr9","ledyr10","ledyr11","ledyr12","ledyr13","ledyr14","ledyr15")

led_data%>%
  group_by(study)%>%
  count(is.na(ledbl))



#----MDSUPDRS part3-----

mdsupdrs3<-data1%>%
  select("study","idpicc","originalid","incidencecase","mdsupdrspart3bltotalconvertedasa","mdsupdrspart3yr1totalconvertedas","mdsupdrspart3yr2totalconvertedas","mdsupdrspart3yr3totalconvertedas","mdsupdrspart3yr4totalconvertedas","mdsupdrspart3yr5totalconvertedas","mdsupdrspart3yr6totalconvertedas","mdsupdrspart3yr7totalconvertedas","mdsupdrspart3yr8totalconvertedas","mdsupdrspart3yr9totalconvertedas","mdsupdrspart3yr10totalconverteda","mdsupdrspart3yr11totalconverteda","mdsupdrspart3yr12totalconverteda")

mdsupdrs3%>%
  group_by(study)%>%
  count(is.na(mdsupdrspart3bltotalconvertedasa))

#All studies measured mdsupdrs part 3

#----MDSUPDRS part1-----

updrspart1_data<-data1%>%
  select("study","updrsblpart1","updrsyr1part1","updrsyr2part1","updrsyr3part1","updrsyr4part1","updrsyr5part1","updrsyr6part1","updrsyr7part1","updrsyr8part1","updrsyr9part1","updrsyr10part1")

updrspart1_data%>%
  group_by(study)%>%
  count(is.na(updrsblpart1))

#ICICLE missing all updrs part1
```

```{r change long format (longitudinal)}

#get variables that need. 

data2<-data1%>%
  select("study","idpicc","originalid","incidencecase","agebl","sex","smoking","comorbiditylistbl","charlsonbl",
         "ledbl","ledyr1","ledyr2","ledyr3","ledyr4","ledyr5","ledyr6","ledyr7","ledyr8","ledyr9","ledyr10","ledyr11","ledyr12","ledyr13","ledyr14","ledyr15",
         "mdsupdrspart3bltotalconvertedasa","mdsupdrspart3yr1totalconvertedas","mdsupdrspart3yr2totalconvertedas","mdsupdrspart3yr3totalconvertedas","mdsupdrspart3yr4totalconvertedas","mdsupdrspart3yr5totalconvertedas","mdsupdrspart3yr6totalconvertedas","mdsupdrspart3yr7totalconvertedas","mdsupdrspart3yr8totalconvertedas","mdsupdrspart3yr9totalconvertedas","mdsupdrspart3yr10totalconverteda","mdsupdrspart3yr11totalconverteda","mdsupdrspart3yr12totalconverteda",
         "mmsebltotal","mmseyr1total","mmseyr2total","mmseyr3total","mmseyr4total","mmseyr4total","mmseyr5total","mmseyr6total","mmseyr7total","mmseyr8total","mmseyr9total","mmseyr10total","mmseyr11total","mmseyr11total","mmseyr12total",
         "hybl","hyyr1","hyyr2","hyyr3","hyyr4","hyyr5","hyyr6","hyyr7","hyyr8","hyyr9","hyyr10","hyyr11","hyyr12",
         "datevisitbl","datevisityr1","datevisityr2","datevisityr3","datevisityr4","datevisityr5","datevisityr6","datevisityr7","datevisityr8","datevisityr9","datevisityr10","datevisityr11","datevisityr12","datevisityr13","datevisityr14","datevisityr15",
         "datelastseen","datelastknownalive","datedeath","datedementia","datelost")

  
#-----create follow-up times in years----

data2$year1<-as.numeric(as.Date(as.character(data1$datevisityr1), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year2<-as.numeric(as.Date(as.character(data1$datevisityr2), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25


data2$year3<-as.numeric(as.Date(as.character(data1$datevisityr3), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year4<-as.numeric(as.Date(as.character(data1$datevisityr4), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year5<-as.numeric(as.Date(as.character(data1$datevisityr5), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year6<-as.numeric(as.Date(as.character(data1$datevisityr6), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year7<-as.numeric(as.Date(as.character(data1$datevisityr7), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year8<-as.numeric(as.Date(as.character(data1$datevisityr8), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year9<-as.numeric(as.Date(as.character(data1$datevisityr9), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year10<-as.numeric(as.Date(as.character(data1$datevisityr10), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year11<-as.numeric(as.Date(as.character(data1$datevisityr11), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year12<-as.numeric(as.Date(as.character(data1$datevisityr12), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year13<-as.numeric(as.Date(as.character(data1$datevisityr13), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year14<-as.numeric(as.Date(as.character(data1$datevisityr14), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25

data2$year15<-as.numeric(as.Date(as.character(data1$datevisityr15), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d"))/365.25


#-----create events/censoring years------

data2<-data2 %>%
  mutate(t=datedeath)%>%           
  mutate(t=coalesce(t,datelastknownalive))%>%
  mutate(t=coalesce(t,datelastseen))

#if patients have the date of death then t is the date of death. If patients without date of death, then the censoring date will be the date of last know alive. If patients without the date of last know alive then the censoring date will be the date last seen. Because I found some patients with date of lost is much later than the last seen, but the measurement stop in the last seen visiting year.


#sum(is.na(data2$t)) # 0 missing


data2$cens<-ifelse(is.na(data2$datedeath),0,1)  #0=right censored, 1=event 

data2$tt<-as.Date(as.character(data2$t), format="%Y-%m-%d")-
                as.Date(as.character(data2$datevisitbl), format="%Y-%m-%d")

data2$tt<-as.numeric(data2$tt)

data2$years<-data2$tt/365.25  #1223 rows

data2%>%
  filter(tt==0)%>%
  group_by(study)%>%
  count()            #CamPalGN 7 ParkWest 2 PICNICS 13 (All only has one time visit) 

data2<-data2%>%
  filter(data2$years>0) #1201 removed 22 patients 


#-----long format-----

years_long<-data2%>%
  pivot_longer(
    cols = `year1`:`year15`,
    names_to = "visityear",
    values_to = "followupyears",
    values_transform = ~ as.numeric(gsub(",", "", .x)),
    values_drop_na = T
  )

#change mmseyr to year1 



colnames(MMSE_data)[6:17]<-c("year1","year2","year3","year4",
                          "year5","year6","year7","year8",
                          "year9","year10","year11","year12")

mmse_long<-MMSE_data%>%
  pivot_longer(
    cols = `year1`:`year12`,
    names_to = "visityear",
    values_to = "mmse",
    values_transform = ~ as.numeric(gsub(",", "", .x)),
    values_drop_na = T
  )

colnames(mdsupdrs3)[6:17]<-c("year1","year2","year3","year4",
                          "year5","year6","year7","year8",
                          "year9","year10","year11","year12")

mdsupdrs_long<-mdsupdrs3%>%
  pivot_longer(
    cols = `year1`:`year12`,
    names_to = "visityear",
    values_to = "mdsupdrs3",
    values_transform = ~ as.numeric(gsub(",", "", .x)),
    values_drop_na = T
  )

colnames(HY_data)[6:17]<-c("year1","year2","year3","year4",
                          "year5","year6","year7","year8",
                          "year9","year10","year11","year12")

hy_long<-HY_data%>%
  pivot_longer(
    cols = `year1`:`year12`,
    names_to = "visityear",
    values_to = "hy",
    values_transform = ~ as.numeric(gsub(",", "", .x)),
    values_drop_na = T
  )


colnames(led_data)[6:20]<-c("year1","year2","year3","year4",
                          "year5","year6","year7","year8",
                          "year9","year10","year11","year12","year13","year14","year15")

led_long<-led_data%>%
  pivot_longer(
    cols = `year1`:`year15`,
    names_to = "visityear",
    values_to = "led",
    values_transform = ~ as.numeric(gsub(",", "", .x)),
    values_drop_na = T
  )


```

```{r cmobine long format datasets}
#-----combine all long tidy------

nrow(years_long)  #5091
nrow(mmse_long)   #4378
nrow(mdsupdrs_long)  #3827
nrow(hy_long)    #5037
nrow(led_long) #5053

years_long.new<-years_long%>%
  select("study","idpicc","originalid","incidencecase","agebl","sex","smoking","comorbiditylistbl","charlsonbl","mdsupdrspart3bltotalconvertedasa","mmsebltotal","hybl","cens","years","followupyears","visityear")


mmse_long.new<-mmse_long%>%
  select("study","idpicc","visityear","mmse")


mdsupdrs_long.new<-mdsupdrs_long%>%
  select("study","idpicc","visityear","mdsupdrs3")

hy_long.new<-hy_long%>%
  select("study","idpicc","visityear","hy")

led_long.new<-led_long%>%
  select("study","idpicc","visityear","led")

A<-merge(years_long.new, mmse_long.new, by = c("study","idpicc","visityear"),all.x = T,all.y = T)

B<-merge(A, mdsupdrs_long.new, by = c("study","idpicc","visityear"),all.x = T,all.y = T)

C<-merge(B,hy_long.new, by = c("study","idpicc","visityear"),all.x = T,all.y = T) 

data_long<-merge(C,led_long.new, by = c("study","idpicc","visityear"),all.x = T,all.y = T) 

data_long<-data_long[order(data_long$idpicc,data_long$visityear), ]

```


```{r check missing in baseline variables}

#----check age----

data_long%>%
  group_by(study)%>%
  count(is.na(agebl))
#10 patints in PINE missing agebl

data_long%>%
  filter(study=="ParkWest")%>%
  filter(is.na(agebl))
#idpicc 1170 1235 1261 1116 1132 1136 1151 1152 1156 1161
#343 382 384 390 405
#534


#1170 The follow-up time is end in 10 years,patient has mmse value on 11 and 12 years. 
#1235 The follow-up time is end in 9 years, patient has mmse value on 10 and 11 years.
#1261 The follow-up time is end in 9 years, patient has mmse value on 10 and 11 years.

#1116 The follow-up time is end in 11 years, patients has led value at 12 years.
#1132 The follow-up time is end in 5 years, patients has led value at 6 years.
#1136 The follow-up time is end in 6 years, patients has led value at 7 years.
#1151 doesn't have follow-up
#1152 The follow-up time is end in 5 years, patients has led value at 6 years.
#1156 The follow-up time is end in 2 years, patients has led value at 3 years.
#1161 The follow-up time is end in 11 years, patients has led value at 12 years.
#... same with other idpicc not list here anymore

#------remove value outside the last seen date-----

#Due to the data just medical records not real follow-up we remove it

data_long<-data_long[!is.na(data_long$agebl),]

#----check sex----

data_long%>%
  group_by(study)%>%
  count(is.na(sex))
#same problem as agebl in PINE

#----check smoke----

data_long%>%
  group_by(study)%>%
  count(is.na(smoking))

#PINE has the highest missing 61

data2%>%
  group_by(study)%>%
  count(is.na(smoking))

#-----check comorbidity----

data2%>%
  group_by(study)%>%
  count(is.na(charlsonbl))

```

```{r check how many after 10 years}

#There only PINE study have years 11 and further follow-up


data2%>%
  group_by(study)%>%
  count(year11)

check<-data2%>%
  filter(study=="CamPalGN")

#We only keep data to follow up year 10

data_long.new<-data_long[data_long$years<11,]
  

```


```{r check pre longitudinal outcome mmse}

data_plot<-data_long.new[order(data_long$followupyears), ]

mmse_plot<-data_plot%>%
   select("study","idpicc","originalid","followupyears","visityear","mmse")

mmse_plot<-mmse_plot[complete.cases(mmse_plot),]

mmse_plot<-mmse_plot%>%
  arrange(idpicc,followupyears)


ggplot(data = mmse_plot, aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()

#check the one with all zero MMSE in followup years

mmse_plot%>%
  filter(mmse==0)

#1602
#1666
#1677

mmse_plot%>%
  filter(idpicc==1602) #21 4 0 0 0 0 0 

mmse_plot%>%
  filter(idpicc==1666) # 0 0

mmse_plot%>%
  filter(idpicc==1677) # 19 18 10 0 0


ggplot(data = subset(mmse_plot,study=="CamPalGN"), aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()

ggplot(data = subset(mmse_plot,study=="ICICLE"), aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()

ggplot(data = subset(mmse_plot,study=="ParkWest"), aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()

ggplot(data = subset(mmse_plot,study=="PICNICS"), aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()

ggplot(data = subset(mmse_plot,study=="NYPUM"), aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()

ggplot(data = subset(mmse_plot,study=="PINE"), aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()



PINE_mmse<-subset(mmse_plot,study=="PINE")

PINE_mmse%>%
  filter(followupyears>10)%>%
  arrange(idpicc,followupyears)

#1172 in year 11 is 0,but year 12 is 2

PINE_mmse%>%
  filter(idpicc==1172) #year 8 & 9 is 6 but year 10 is 16 #check record is correct




```


```{r check pre longitudinal outcome mdsupdrs}

mdsupdrs3_plot<-data_plot%>%
   select("study","idpicc","originalid","followupyears","visityear","mdsupdrs3")

mdsupdrs3_plot<-mdsupdrs3_plot[complete.cases(mdsupdrs3_plot),]

mdsupdrs3_plot<-mdsupdrs3_plot%>%
                 arrange(idpicc,followupyears)

ggplot(data = mdsupdrs3_plot, aes(x = followupyears, y = mdsupdrs3,group=idpicc))+
    geom_line()


ggplot(data = subset(mdsupdrs3_plot,study=="CamPalGN"), aes(x = followupyears, y = mdsupdrs3,group=idpicc))+
    geom_line()

ggplot(data = subset(mdsupdrs3_plot,study=="ICICLE"), aes(x = followupyears, y = mdsupdrs3,group=idpicc))+
    geom_line()

ggplot(data = subset(mdsupdrs3_plot,study=="ParkWest"), aes(x = followupyears, y = mdsupdrs3,group=idpicc))+
    geom_line()


ggplot(data = subset(mdsupdrs3_plot,study=="NYPUM"), aes(x = followupyears, y = mdsupdrs3,group=idpicc))+
    geom_line()


ggplot(data = subset(mdsupdrs3_plot,study=="PICNICS"), aes(x = followupyears, y = mdsupdrs3,group=idpicc))+
    geom_line()

ggplot(data = subset(mdsupdrs3_plot,study=="PINE"), aes(x = followupyears, y = mdsupdrs3,group=idpicc))+
    geom_line()



```


```{r check pre longitudinal outcome HY}

hy_plot<-data_plot%>%
   select("study","idpicc","originalid","followupyears","visityear","hy")

hy_plot<-hy_plot[complete.cases(hy_plot),]

hy_plot<-hy_plot%>%
        arrange(idpicc,followupyears)

ggplot(data = hy_plot, aes(x = followupyears, y = hy,group=idpicc))+
    geom_line()

ggplot(data = subset(hy_plot,study=="CamPalGN"), aes(x = followupyears, y = hy,group=idpicc))+
    geom_line()

ggplot(data = subset(hy_plot,study=="ICICLE"), aes(x = followupyears, y = hy,group=idpicc))+
    geom_line()

ggplot(data = subset(hy_plot,study=="ParkWest"), aes(x = followupyears, y = hy,group=idpicc))+
    geom_line()

ggplot(data = subset(hy_plot,study=="NYPUM"), aes(x = followupyears, y = hy,group=idpicc))+
    geom_line()

ggplot(data = subset(hy_plot,study=="PICNICS"), aes(x = followupyears, y = hy,group=idpicc))+
    geom_line()

ggplot(data = subset(hy_plot,study=="PINE"), aes(x = followupyears, y = hy,group=idpicc))+
    geom_line()

```


```{r check pre longitudinal outcome led}

led_plot<-data_plot%>%
   select("study","idpicc","originalid","followupyears","visityear","led")

led_plot<-led_plot[complete.cases(led_plot),]

led_plot<-led_plot%>%
                 arrange(idpicc,followupyears)

ggplot(data = led_plot, aes(x = followupyears, y = led,group=idpicc))+
    geom_line()


ggplot(data = subset(led_plot,study=="CamPalGN"), aes(x = followupyears, y = led,group=idpicc))+
    geom_line()

ggplot(data = subset(led_plot,study=="ICICLE"), aes(x = followupyears, y = led,group=idpicc))+
    geom_line()

ggplot(data = subset(led_plot,study=="ParkWest"), aes(x = followupyears, y = led,group=idpicc))+
    geom_line()


ggplot(data = subset(led_plot,study=="NYPUM"), aes(x = followupyears, y = led,group=idpicc))+
    geom_line()


ggplot(data = subset(led_plot,study=="PICNICS"), aes(x = followupyears, y = led,group=idpicc))+
    geom_line()

ggplot(data = subset(led_plot,study=="PINE"), aes(x = followupyears, y = led,group=idpicc))+
    geom_line()



```


```{r }

#I think I can built two models, one is joint model, with updrs/led/mmse
#The other is HY in landmarking


```



```{r try randome effect linear}

ggplot(data = mmse_plot, aes(x = followupyears, y = mmse))+
    geom_point()+
    geom_smooth(method = "loess")

ggplot(data = mdsupdrs3_plot, aes(x = followupyears, y = mdsupdrs3))+
    geom_point()+
    geom_smooth(method = "loess")

ggplot(data = hy_plot, aes(x = followupyears, y = hy))+
    geom_point()+
    geom_smooth(method = "loess")

library(nlme)

lme()
```
