---
title: "Dementia linear mixed model"
output: html_document
date: "2023-08-08"
---

```{r library}

library(nlme)
#library(grid)
#library(gridExtra)
library(patchwork)#arrange plot
```


```{r randomly select the second imputation}

#Need to remove the MMSE records after event (dementia)

data_long.2.new<-data_long.2%>%
                 filter(years>followupyears)

#Because PINE had biggest sample size, so the PINE should be as reference group

```


```{r check longitudinal outcome mmse}

data_plot<-data_long.2.new[order(data_long.2.new$followupyears), ]

mmse_plot<-data_plot%>%
   select("study","id","idpicc","followupyears","visityear","mmse")%>%
   filter(followupyears!=0)

mmse_plot<-mmse_plot%>%
  arrange(id,followupyears)


#ggplot(data = mmse_plot, aes(x = followupyears, y = mmse,group=id))+
#    geom_line()

#check the one with all zero MMSE in followup years


p1<-ggplot(data = subset(mmse_plot,study=="CamPalGN"), aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()+
    xlab("follow-up years (CamPalGN)")+
    ylab("MMSE")+
    theme_bw()

p2<-ggplot(data = subset(mmse_plot,study=="ParkWest"), aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()+
    xlab("follow-up years (ParkWest)")+
    ylab("MMSE")+
    theme_bw()

p3<-ggplot(data = subset(mmse_plot,study=="PICNICS"), aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()+
    xlab("follow-up years (PICNICS)")+
    ylab("MMSE")+
    theme_bw()

p4<-ggplot(data = subset(mmse_plot,study=="NYPUM"), aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()+
    xlab("follow-up years (NYPUM)")+
    ylab("MMSE")+
    theme_bw()

p5<-ggplot(data = subset(mmse_plot,study=="PINE"), aes(x = followupyears, y = mmse,group=idpicc))+
    geom_line()+
    xlab("follow-up years (PINE)")+
    ylab("MMSE")+
    theme_bw()

p6<-ggplot(data = mmse_plot, aes(x = followupyears, y = mmse,group=id))+
    geom_line()+
    xlab("follow-up years (PICC)")+
    ylab("MMSE")+
    theme_bw()

#png("MMSE1.png",width = 3000,height =1500,res = 400)

p1+p2+p3+p4+p5+p6

#grid.arrange(p1,p2,p3,p4,ncol=2) not need 

#dev.off()

#A<-mmse_plot%>%
#  filter(study=="PICNICS")%>%
#  filter(mmse<20)

#8 lower than 20 in PICNICS

#length(unique(A$idpicc))

```


```{r Create the fitting model dataset}

#-----remove variables that don't need----

data_long.2.fit<-data_long.2.new%>%
  select(study,idpicc,agebl,sex,yearseducation,followupyears,mmse,mdsupdrspart3bltotalconvertedasa,hybl,hallucinationsindex,cognitiveindex,years,cens)

data.baseline.2.fit<-data.baseline.2%>%
  select(study,idpicc,agebl,sex,yearseducation,mdsupdrspart3bltotalconvertedasa,hybl,hallucinationsindex,cognitiveindex,years,cens)

#try add smoking into the data
data_long.2.fit<-data_long.2.new%>%
  select(study,idpicc,agebl,sex,yearseducation,smoking,followupyears,mmse,mdsupdrspart3bltotalconvertedasa,hybl,hallucinationsindex,cognitiveindex,years,cens)

data.baseline.2.fit<-data.baseline.2%>%
  select(study,idpicc,agebl,sex,yearseducation,smoking,mdsupdrspart3bltotalconvertedasa,hybl,hallucinationsindex,cognitiveindex,years,cens)


#check the study levels

levels(data_long.2.fit$study)
levels(data.baseline.2.fit$study)

#----changing the reference level to PINE, as the PINE has the biggest sample size of patients with event

data.baseline.2.fit$study<-factor(data.baseline.2.fit$study,levels=c("PINE","CamPalGN","NYPUM","ParkWest","PICNICS")) #put PINE as the first level

levels(data.baseline.2.fit$study)

data.baseline.2.fit%>%
  group_by(study)%>%
  count(cens)


data_long.2.fit$study<-factor(data_long.2.fit$study,levels=c("PINE","CamPalGN","NYPUM","ParkWest","PICNICS")) #put PINE as the first level

levels(data_long.2.fit$study)


```



```{r create the lme data and fit model}

#setdiff(unique(data.baseline.2$id),unique(data_long.2.new$id))

length(unique(data_long.2.new$idpicc))
nrow(data.baseline.2)

#----test to see which one works------

#As years of education only missing 11, so the best model select from first imputation data set can view as general

lme.1<-lme(mmse~ agebl+yearseducation, random = ~ followupyears | idpicc, data=data_long.2.fit) 

lme.2<-lme(mmse~ agebl+sex+yearseducation, random = ~ followupyears | idpicc, data=data_long.2.fit)

lme.3<-lme(mmse~ study+agebl+sex+yearseducation, random = ~ followupyears | idpicc, data=data_long.2.fit)

lme.4<-lme(mmse~ study*agebl+sex+yearseducation, random = ~ followupyears | idpicc, data=data_long.2.fit)

lme.5<-lme(mmse~ agebl+sex+study*yearseducation, random = ~ followupyears | idpicc, data=data_long.2.fit)

lme.6<-lme(mmse~ agebl+sex*study+yearseducation, random = ~ followupyears | idpicc, data=data_long.2.fit)

#summary(lme.3)

#put PINE as the ref

round(AIC(lme.1),2) 
AIC(lme.2) 
AIC(lme.3) 
AIC(lme.4) 
AIC(lme.5) 
AIC(lme.6)

BIC(lme.1) 
BIC(lme.2)
BIC(lme.3) 
BIC(lme.4) 
BIC(lme.5) 
BIC(lme.6)

#choose lme.3

#variables in lme: sex agebl yearseducation followupyears idpicc
#variables in Cox: agebl sex yearseducation mdsupdrspart3bltotalconvertedasa hybl hallucinationsindex cognitiveindex strata(study)
```

```{r joint model}
#----joint model---

lme<-lme(mmse~ study+agebl+sex+yearseducation, random = ~ followupyears | idpicc, data=data_long.2.fit)

#----Stratified Cox (not chose)-----

#baseline.cox.1<-coxph(Surv(years,cens)~agebl+sex+yearseducation+mdsupdrspart3bltotalconvertedasa+hybl+hallucinationsindex+cognitiveindex+strata(study),data=data.baseline.2.fit, x = TRUE,model = TRUE)
#jointFit.1<-jm(baseline.cox.1, lme, time_var = "followupyears")


#---Study as fixed effect----

baseline.cox.2<-coxph(Surv(years,cens)~agebl+sex+yearseducation+mdsupdrspart3bltotalconvertedasa+hybl+hallucinationsindex+cognitiveindex+study,data=data.baseline.2.fit, x = TRUE,model = TRUE)

baseline.cox.3<-coxph(Surv(years,cens)~agebl+sex+yearseducation+mdsupdrspart3bltotalconvertedasa+hybl+hallucinationsindex+cognitiveindex+study+smoking,data=data.baseline.2.fit, x = TRUE,model = TRUE)

jointFit.2<-jm(baseline.cox.2, lme, time_var = "followupyears") 

jointFit.3<-jm(baseline.cox.3, lme, time_var = "followupyears") 

summary(jointFit.2)

#

compare_jm(jointFit.2,jointFit.3)

#Chose jointFit.1

#----update JM----

#jointFit.2.update1<- update(jointFit.2,
#                       functional_forms = ~ value(mmse) * study)

#summary(jointFit.2.update1)

#compare_jm(jointFit.2,jointFit.2.update1)

#The update one isn't congervence cannot use

traceplot(jointFit.2)


```

```{r predict 1131}

#randomly select patient as example to illustrate

predict.data<-data_long.2.fit[data_long.2.fit$idpicc == 1131,]  #idpicc 1131 event year is 6

#----Only baseline information-----

predict.data.time.0<-predict.data[predict.data$followupyears==0,] 

predict.data.time.0$cens<-0 #not event

predict.data.time.0$years<-0 #predict time at 0 years

predMMSE.0<-predict(jointFit.2,newdata = predict.data.time.0,times = seq(0,3, length.out=20),return_newdata = T) #for future time point

predSurv.0<-predict(jointFit.2,newdata = predict.data.time.0,process = "event",times = seq(0,3, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.0,predSurv.0)


#-----From baseline up to 1 year-----

predict.data.time.1<-predict.data[predict.data$followupyears<2,] 

predict.data.time.1$cens<-0 #not event

predict.data.time.1$years<-1.2 

predMMSE.1<-predict(jointFit.2,newdata = predict.data.time.1,times = seq(1.2,4, length.out=20),return_newdata = T) #for future time point

predSurv.1<-predict(jointFit.2,newdata = predict.data.time.1,process = "event",times = seq(1.2,4, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.1,predSurv.1)


#-----From baseline up to 2 year-----

predict.data.time.2<-predict.data[predict.data$followupyears<3,] 

predict.data.time.2$cens<-0 #not event

predict.data.time.2$years<-2.1 

predMMSE.2<-predict(jointFit.2,newdata = predict.data.time.2,times = seq(2.1,5, length.out=20),return_newdata = T) #for future time point

predSurv.2<-predict(jointFit.2,newdata = predict.data.time.2,process = "event",times = seq(2.1,5, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.2,predSurv.2)



#------From baseline up to 3 years-----

predict.data.time.3<-predict.data[predict.data$followupyears<4,] 

predict.data.time.3$cens<-0 #not event

predict.data.time.3$years<-3.1 

#predict for longitudinal outcomes

predMMSE.3<-predict(jointFit.2,newdata = predict.data.time.3,times = seq(3.1,6, length.out=20),return_newdata = T) #for future time point

predSurv.3<-predict(jointFit.2,newdata = predict.data.time.3,process = "event",times = seq(3.1,6, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.3,predSurv.3)


#------From baseline up to 4 years-----

predict.data.time.4<-predict.data[predict.data$followupyears<5,] 

predict.data.time.4$cens<-0 #not event

predict.data.time.4$years<-4 

#predict for longitudinal outcomes

predMMSE.4<-predict(jointFit.2,newdata = predict.data.time.4,times = seq(4,7, length.out=20),return_newdata = T) #for future time point

predSurv.4<-predict(jointFit.2,newdata = predict.data.time.4,process = "event",times = seq(4,7, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.4,predSurv.4)


#------From baseline up to 5 years-----

predict.data.time.5<-predict.data[predict.data$followupyears<6,] 

predict.data.time.5$cens<-0 #not event

predict.data.time.5$years<-5.04 

#predict for longitudinal outcomes

predMMSE.5<-predict(jointFit.2,newdata = predict.data.time.5,times = seq(5.04,8, length.out=20),return_newdata = T) #for future time point

predSurv.5<-predict(jointFit.2,newdata = predict.data.time.5,process = "event",times = seq(5.04,8, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.5,predSurv.5)


#----Arrange plot----

#png("JMpred1.png",width = 4000,height =1500,res = 400)

#par(mfrow=c(1,3))

plot(predMMSE.0,predSurv.0,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.1,predSurv.1,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.2,predSurv.2,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)

#dev.off()

#png("JMpred2.png",width = 4000,height =1500,res = 400)

#par(mfrow=c(1,3))

plot(predMMSE.3,predSurv.3,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.4,predSurv.4,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.5,predSurv.5,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)

#dev.off()
```


```{r predict 79}

#randomly select patient as example to illustrate

predict.data<-data_long.2.fit[data_long.2.fit$idpicc == 79,]  #idpicc 14 event year is 7

#----Only baseline information-----

predict.data.time.0<-predict.data[predict.data$followupyears==0,] 

predict.data.time.0$cens<-0 #not event

predict.data.time.0$years<-0 #predict time at 0 years

predMMSE.0<-predict(jointFit.2,newdata = predict.data.time.0,times = seq(0,3, length.out=20),return_newdata = T) #for future time point

predSurv.0<-predict(jointFit.2,newdata = predict.data.time.0,process = "event",times = seq(0,3, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.0,predSurv.0)


#-----From baseline up to 3 year-----

predict.data.time.2<-predict.data[predict.data$followupyears<4,] 

predict.data.time.2$cens<-0 #not event

predict.data.time.2$years<-3 

predMMSE.2<-predict(jointFit.2,newdata = predict.data.time.2,times = seq(3,6, length.out=20),return_newdata = T) #for future time point

predSurv.2<-predict(jointFit.2,newdata = predict.data.time.2,process = "event",times = seq(3,6, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.2,predSurv.2)


#------From baseline up to 5 years-----

predict.data.time.4<-predict.data[predict.data$followupyears<5,] 

predict.data.time.4$cens<-0 #not event

predict.data.time.4$years<-4.9 

#predict for longitudinal outcomes

predMMSE.4<-predict(jointFit.2,newdata = predict.data.time.4,times = seq(4.9,7.9, length.out=20),return_newdata = T) #for future time point

predSurv.4<-predict(jointFit.2,newdata = predict.data.time.4,process = "event",times = seq(4.9,7.9, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.4,predSurv.4)


#------From baseline up to 7 years-----

predict.data.time.5<-predict.data[predict.data$followupyears<7,] 

predict.data.time.5$cens<-0 #not event

predict.data.time.5$years<-6.8

#predict for longitudinal outcomes

predMMSE.5<-predict(jointFit.2,newdata = predict.data.time.5,times = seq(6.8,9.8, length.out=20),return_newdata = T) #for future time point

predSurv.5<-predict(jointFit.2,newdata = predict.data.time.5,process = "event",times = seq(6.8,9.8, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.5,predSurv.5)


#----Arrange plot----

png("JMpred1.Cam.png",width = 4000,height =1500,res = 400)

par(mfrow=c(1,4))

plot(predMMSE.0,predSurv.0,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.2,predSurv.2,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.4,predSurv.4,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.5,predSurv.5,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)

dev.off()

data%>%
  filter(idpicc==79)
```


```{r predict 348}

#randomly select patient as example to illustrate

predict.data<-data_long.2.fit[data_long.2.fit$idpicc == 348,]  #idpicc 1131 event year is 9

#----Only baseline information-----

predict.data.time.0<-predict.data[predict.data$followupyears==0,] 

predict.data.time.0$cens<-0 #not event

predict.data.time.0$years<-0 #predict time at 0 years

predMMSE.0<-predict(jointFit.2,newdata = predict.data.time.0,times = seq(0,3, length.out=20),return_newdata = T) #for future time point

predSurv.0<-predict(jointFit.2,newdata = predict.data.time.0,process = "event",times = seq(0,3, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.0,predSurv.0)


#-----From baseline up to 1 year-----

predict.data.time.1<-predict.data[predict.data$followupyears<2,] 

predict.data.time.1$cens<-0 #not event

predict.data.time.1$years<-1 

predMMSE.1<-predict(jointFit.2,newdata = predict.data.time.1,times = seq(1,4, length.out=20),return_newdata = T) #for future time point

predSurv.1<-predict(jointFit.2,newdata = predict.data.time.1,process = "event",times = seq(1,4, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.1,predSurv.1)


#-----From baseline up to 2 year-----

predict.data.time.2<-predict.data[predict.data$followupyears<3,] 

predict.data.time.2$cens<-0 #not event

predict.data.time.2$years<-2 

predMMSE.2<-predict(jointFit.2,newdata = predict.data.time.2,times = seq(2,5, length.out=20),return_newdata = T) #for future time point

predSurv.2<-predict(jointFit.2,newdata = predict.data.time.2,process = "event",times = seq(2,5, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.2,predSurv.2)



#------From baseline up to 3 years-----

predict.data.time.3<-predict.data[predict.data$followupyears<4,] 

predict.data.time.3$cens<-0 #not event

predict.data.time.3$years<-3.04 

#predict for longitudinal outcomes

predMMSE.3<-predict(jointFit.2,newdata = predict.data.time.3,times = seq(3.04,6, length.out=20),return_newdata = T) #for future time point

predSurv.3<-predict(jointFit.2,newdata = predict.data.time.3,process = "event",times = seq(3.04,6, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.3,predSurv.3)


#------From baseline up to 4 years-----

predict.data.time.4<-predict.data[predict.data$followupyears<5,] 

predict.data.time.4$cens<-0 #not event

predict.data.time.4$years<-4.1 

#predict for longitudinal outcomes

predMMSE.4<-predict(jointFit.2,newdata = predict.data.time.4,times = seq(4.1,7, length.out=20),return_newdata = T) #for future time point

predSurv.4<-predict(jointFit.2,newdata = predict.data.time.4,process = "event",times = seq(4.1,7, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.4,predSurv.4)


#------From baseline up to 5 years-----

predict.data.time.5<-predict.data[predict.data$followupyears<6,] 

predict.data.time.5$cens<-0 #not event

predict.data.time.5$years<-5.04 

#predict for longitudinal outcomes

predMMSE.5<-predict(jointFit.2,newdata = predict.data.time.5,times = seq(5.04,8, length.out=20),return_newdata = T) #for future time point

predSurv.5<-predict(jointFit.2,newdata = predict.data.time.5,process = "event",times = seq(5.04,8, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.5,predSurv.5)


#------From baseline up to 6 years-----

predict.data.time.6<-predict.data[predict.data$followupyears<7,] 

predict.data.time.6$cens<-0 #not event

predict.data.time.6$years<-6.04 

#predict for longitudinal outcomes

predMMSE.6<-predict(jointFit.2,newdata = predict.data.time.6,times = seq(6.04,9, length.out=20),return_newdata = T) #for future time point

predSurv.6<-predict(jointFit.2,newdata = predict.data.time.6,process = "event",times = seq(6.04,9, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.6,predSurv.6)


#------From baseline up to 8 years-----

predict.data.time.8<-predict.data[predict.data$followupyears<8,] 

predict.data.time.8$cens<-0 #not event

predict.data.time.8$years<-8 

#predict for longitudinal outcomes

predMMSE.8<-predict(jointFit.2,newdata = predict.data.time.8,times = seq(8,10, length.out=20),return_newdata = T) #for future time point

predSurv.8<-predict(jointFit.2,newdata = predict.data.time.8,process = "event",times = seq(8,10, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.8,predSurv.8)


#----Arrange plot----

png("JMpred1.NY.png",width = 4000,height =1500,res = 400)

par(mfrow=c(1,4))

plot(predMMSE.0,predSurv.0,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.1,predSurv.1,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.2,predSurv.2,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.3,predSurv.3,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)

dev.off()

png("JMpred2.NY.png",width = 4000,height =1500,res = 400)

par(mfrow=c(1,4))

plot(predMMSE.4,predSurv.4,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.5,predSurv.5,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.6,predSurv.6,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.8,predSurv.8,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)

dev.off()

data1%>%
  filter(idpicc==348)
```



```{r predict 492}

#randomly select patient as example to illustrate

predict.data<-data_long.2.fit[data_long.2.fit$idpicc == 492,]  #idpicc 1131 event year is 9

#----Only baseline information-----

predict.data.time.0<-predict.data[predict.data$followupyears==0,] 

predict.data.time.0$cens<-0 #not event

predict.data.time.0$years<-0 #predict time at 0 years

predMMSE.0<-predict(jointFit.2,newdata = predict.data.time.0,times = seq(0,3, length.out=20),return_newdata = T) #for future time point

predSurv.0<-predict(jointFit.2,newdata = predict.data.time.0,process = "event",times = seq(0,3, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.0,predSurv.0)


#-----From baseline up to 1 year-----

predict.data.time.1<-predict.data[predict.data$followupyears<2,] 

predict.data.time.1$cens<-0 #not event

predict.data.time.1$years<-1 

predMMSE.1<-predict(jointFit.2,newdata = predict.data.time.1,times = seq(1,4, length.out=20),return_newdata = T) #for future time point

predSurv.1<-predict(jointFit.2,newdata = predict.data.time.1,process = "event",times = seq(1,4, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.1,predSurv.1)


#-----From baseline up to 3 year-----

predict.data.time.2<-predict.data[predict.data$followupyears<3,] 

predict.data.time.2$cens<-0 #not event

predict.data.time.2$years<-3 

predMMSE.2<-predict(jointFit.2,newdata = predict.data.time.2,times = seq(3,6, length.out=20),return_newdata = T) #for future time point

predSurv.2<-predict(jointFit.2,newdata = predict.data.time.2,process = "event",times = seq(3,6, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.2,predSurv.2)


#------From baseline up to 5 years-----

predict.data.time.5<-predict.data[predict.data$followupyears<6,] 

predict.data.time.5$cens<-0 #not event

predict.data.time.5$years<-5 

#predict for longitudinal outcomes

predMMSE.5<-predict(jointFit.2,newdata = predict.data.time.5,times = seq(5,8, length.out=20),return_newdata = T) #for future time point

predSurv.5<-predict(jointFit.2,newdata = predict.data.time.5,process = "event",times = seq(5,8, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.5,predSurv.5)



#----Arrange plot----

png("JMpred1.PA.png",width = 4000,height =1500,res = 400)

par(mfrow=c(1,4))

plot(predMMSE.0,predSurv.0,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.1,predSurv.1,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.2,predSurv.2,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.5,predSurv.5,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)

dev.off()


data1%>%
  filter(idpicc==492)
```




```{r predict 885}

#randomly select patient as example to illustrate

predict.data<-data_long.2.fit[data_long.2.fit$idpicc == 885,]  #idpicc 885 event year is 6

#----Only baseline information-----

predict.data.time.0<-predict.data[predict.data$followupyears==0,] 

predict.data.time.0$cens<-0 #not event

predict.data.time.0$years<-0 #predict time at 0 years

predMMSE.0<-predict(jointFit.2,newdata = predict.data.time.0,times = seq(0,3, length.out=20),return_newdata = T) #for future time point

predSurv.0<-predict(jointFit.2,newdata = predict.data.time.0,process = "event",times = seq(0,3, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.0,predSurv.0)

#-----From baseline up to 3 year-----

predict.data.time.2<-predict.data[predict.data$followupyears<3,] 

predict.data.time.2$cens<-0 #not event

predict.data.time.2$years<-2.4 

predMMSE.2<-predict(jointFit.2,newdata = predict.data.time.2,times = seq(2.4,5, length.out=20),return_newdata = T) #for future time point

predSurv.2<-predict(jointFit.2,newdata = predict.data.time.2,process = "event",times = seq(2.4,5, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.2,predSurv.2)


#------From baseline up to 4 years-----

predict.data.time.4<-predict.data[predict.data$followupyears<4,] 

predict.data.time.4$cens<-0 #not event

predict.data.time.4$years<-3.9 

#predict for longitudinal outcomes

predMMSE.4<-predict(jointFit.2,newdata = predict.data.time.4,times = seq(3.9,7, length.out=20),return_newdata = T) #for future time point

predSurv.4<-predict(jointFit.2,newdata = predict.data.time.4,process = "event",times = seq(3.9,7, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.4,predSurv.4)


#------From baseline up to 5 years-----

predict.data.time.5<-predict.data[predict.data$followupyears<6,] 

predict.data.time.5$cens<-0 #not event

predict.data.time.5$years<-5.5 

#predict for longitudinal outcomes

predMMSE.5<-predict(jointFit.2,newdata = predict.data.time.5,times = seq(5.5,8.5, length.out=20),return_newdata = T) #for future time point

predSurv.5<-predict(jointFit.2,newdata = predict.data.time.5,process = "event",times = seq(5.5,8.5, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.5,predSurv.5)



#----Arrange plot----

png("JMpred1.PIC.png",width = 4000,height =1500,res = 400)

par(mfrow=c(1,4))

plot(predMMSE.0,predSurv.0,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.2,predSurv.2,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.4,predSurv.4,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)
plot(predMMSE.5,predSurv.5,ylab_long = "MMSE",ylab_event = "Cumulative risk of dementia",xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1.5)

dev.off()


data1%>%
  filter(idpicc==885)
```










```{r Not run Cox assumption}

#----Martingale----

rr.0<-residuals(coxph(Surv(years,cens)~1,data=data.baseline.2.fit),type = "martingale")

data.baseline.2.rescheck<-data.baseline.2.fit

data.baseline.2.rescheck$rr.0<-rr.0

p1<-ggplot(data.baseline.2.rescheck,aes(agebl,rr.0))+
  geom_point()+
  geom_smooth(method = "loess",se=T)+
  ylim(c(-1.5,1.5))+
  labs(y="Martingale residuals",x="Age")

p2<-ggplot(data.baseline.2.rescheck,aes(yearseducation,rr.0))+
  geom_point()+
  geom_smooth(method = "loess",se=T)+
  ylim(c(-1.5,1.5))+
  labs(y="Martingale residuals",x="Education(years)")

p3<-ggplot(data.baseline.2.rescheck,aes(mdsupdrspart3bltotalconvertedasa,rr.0))+
  geom_point()+
  geom_smooth(method = "loess",se=T)+
  ylim(c(-1.5,1.5))+
  labs(y="Martingale residuals",x="MDS-UPDRS part3")

p4<-ggplot(data.baseline.2.rescheck,aes(hybl,rr.0))+
  geom_point()+
  geom_smooth(method = "loess",se=T)+
  ylim(c(-1.5,1.5))+
  labs(y="Martingale residuals",x="Hoehn and Yahr")


png("Martingale.png",width = 4000,height =1500,res = 400)
p1+p2+p3
dev.off()

#-----Schoenfeld residuals----

cox.zph(baseline.cox.2) 

test.ph.plot<-cox.zph(baseline.cox.2,transform = "km") 

ggcoxzph(test.ph.plot,var = 1,ylab="Beta(t) for age",caption = NULL)+
  theme_survminer(font.main = 12,font.y = 12,font.x = 12,axis.text.x = element_text(size = 1))

ggcoxzph(test.ph.plot,var = 2,ylab="Beta(t) for sex",caption = NULL)+
  theme_survminer(font.main = 12,font.y = 12,font.x = 12,axis.text.x = element_text(size = 1))

ggcoxzph(test.ph.plot,var = 3,ylab="Beta(t) for education(years)",caption = NULL)+
  theme_survminer(font.main = 12,font.y = 12,font.x = 12,axis.text.x = element_text(size = 1))

ggcoxzph(test.ph.plot,var = 4,ylab="Beta(t) for MDS-UPDRS part3",caption = NULL)+
  theme_survminer(font.main = 12,font.y = 12,font.x = 12,axis.text.x = element_text(size = 1))

ggcoxzph(test.ph.plot,var = 5,ylab="Beta(t) for Hoehn and Yahr",caption = NULL)+
  theme_survminer(font.main = 12,font.y = 12,font.x = 12,axis.text.x = element_text(size = 1))

ggcoxzph(test.ph.plot,var = 6,ylab="Beta(t) for hallucinations",caption = NULL)+
  theme_survminer(font.main = 12,font.y = 12,font.x = 12,axis.text.x = element_text(size = 1))

ggcoxzph(test.ph.plot,var = 7,ylab="Beta(t) for cognitive symptoms",caption = NULL)+
  theme_survminer(font.main = 12,font.y = 12,font.x = 12,axis.text.x = element_text(size = 1))



```

```{r Not run compare JM}

baseline.cox.2<-coxph(Surv(years,cens)~agebl+sex+yearseducation+mdsupdrspart3bltotalconvertedasa+hybl+hallucinationsindex+cognitiveindex+study,data=data.baseline.2.fit, x = TRUE,model = TRUE)

baseline.cox.4<-coxph(Surv(years,cens)~rcs(agebl,3)+sex+yearseducation+mdsupdrspart3bltotalconvertedasa+hybl+hallucinationsindex+cognitiveindex+study,data=data.baseline.2.fit, x = TRUE,model = TRUE)

baseline.cox.5<-coxph(Surv(years,cens)~agebl+sex+rcs(yearseducation,3)+mdsupdrspart3bltotalconvertedasa+hybl+hallucinationsindex+cognitiveindex+study,data=data.baseline.2.fit, x = TRUE,model = TRUE)

baseline.cox.6<-coxph(Surv(years,cens)~agebl+sex+yearseducation+rcs(mdsupdrspart3bltotalconvertedasa,3)+hybl+hallucinationsindex+cognitiveindex+study,data=data.baseline.2.fit, x = TRUE,model = TRUE)

baseline.cox.7<-coxph(Surv(years,cens)~rcs(agebl,3)+sex+yearseducation+rcs(mdsupdrspart3bltotalconvertedasa,3)+hybl+hallucinationsindex+cognitiveindex+study,data=data.baseline.2.fit, x = TRUE,model = TRUE)

jointFit.4<-jm(baseline.cox.4, lme, time_var = "followupyears") 

jointFit.5<-jm(baseline.cox.5, lme, time_var = "followupyears") 

jointFit.6<-jm(baseline.cox.6, lme, time_var = "followupyears") 

jointFit.7<-jm(baseline.cox.7, lme, time_var = "followupyears") 

#

compare_jm(jointFit.2,jointFit.4,jointFit.5,jointFit.6,jointFit.7)

summary(jointFit.7)


#Chose joint7


```





