---
title: "update linear mixed (Dementia)"
output: html_document
date: "2023-11-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(dplyr)
library(tidyr)
library(Hmisc)
library(finalfit)
library(jomo)
library(mice)
library(mitools)
library(rms)
library(mitml)
library(survminer)
library(patchwork) #Arrange plot
library(ggplot2)
library(GGally)
library(gridExtra)
library(png)
library(grid)
library(haven) #read_dta
library(nlme)
library(JMbayes2)
```

```{r data}
#data<-read_dta("PICC dynamic prediction v4.dta")

#write.csv(data,"data.csv",row.names = F)  # need to be csv file, otherwise it fails
datanew<-read.csv("data.csv")  #import data again

#Update data: PCP66 is a male, baseline age is 74.8

datanew$sex[datanew$originalid=="PCP66"]<-0  #male is 0
datanew$agebl[datanew$originalid=="PCP66"]<-74.8

#update P150 H&Y year2 is 2 not 0
#update P757 H&Y year1 is 1.5 not 0

datanew$hyyr2[datanew$originalid=="P150"]<-2
datanew$hyyr1[datanew$originalid=="P757"]<-1.5

#UPDATE P195 need to be exclude cos patient decline the follow-up and without the visit date only mmse value in medical record

datanew<-datanew %>%
  filter(originalid!="P195")

datanew[datanew$originalid=="PCP46",]

```


```{r pre data 1}

#---Adding cognitive symptom and hallucination in longtindinal data----

data1.up<-datanew%>%
  select("study","idpicc","originalid","incidencecase","agebl","sex","hybl",
         "smoking",
         "yearseducation",
         "mmsebltotal","mmseyr1total","mmseyr2total","mmseyr3total","mmseyr4total","mmseyr4total","mmseyr5total","mmseyr6total","mmseyr7total","mmseyr8total","mmseyr9total","mmseyr10total","mmseyr11total","mmseyr11total","mmseyr12total",
         "datevisitbl","datevisityr1","datevisityr2","datevisityr3","datevisityr4","datevisityr5","datevisityr6","datevisityr7","datevisityr8","datevisityr9","datevisityr10","datevisityr11","datevisityr12","datevisityr13","datevisityr14","datevisityr15","datelastseen","datelastknownalive","datedeath","datedementia","datelost","losttofollowup","dead",
         "mdsupdrspart3bltotalconvertedasa","mdsupdrspart3yr1totalconvertedas","mdsupdrspart3yr2totalconvertedas","mdsupdrspart3yr3totalconvertedas","mdsupdrspart3yr4totalconvertedas","mdsupdrspart3yr5totalconvertedas","mdsupdrspart3yr6totalconvertedas",
         "mdsupdrspart3yr7totalconvertedas","mdsupdrspart3yr8totalconvertedas","mdsupdrspart3yr9totalconvertedas",
         "mdsupdrspart3yr9totalconvertedas","mdsupdrspart3yr10totalconverteda","mdsupdrspart3yr11totalconverteda","mdsupdrspart3yr12totalconverteda",
         "mdsupdrsbl101cognitive","mdsupdrsyr1101cognitive","mdsupdrsyr2101cognitive","mdsupdrsyr3101cognitive","mdsupdrsyr4101cognitive","mdsupdrsyr5101cognitive","mdsupdrsyr6101cognitive","mdsupdrsyr7101cognitive","mdsupdrsyr8101cognitive","mdsupdrsyr9101cognitive","mdsupdrsyr10101cognitive","mdsupdrsyr11101cognitive",
         "updrsblitem1intellectual","updrsyr1item1intellectual","updrsyr2item1intellectual","updrsyr3item1intellectual","updrsyr4item1intellectual","updrsyr5item1intellectual","updrsyr6item1intellectual","updrsyr7item1intellectual","updrsyr8item1intellectual","updrsyr9item1intellectual","updrsyr10item1intellectual","updrsyr11item1intellectual",
         "mdsupdrsbl102hallucinations","mdsupdrsyr1102hallucinations","mdsupdrsyr2102hallucinations","mdsupdrsyr3102hallucinations","mdsupdrsyr4102hallucinations","mdsupdrsyr5102hallucinations","mdsupdrsyr6102hallucinations","mdsupdrsyr7102hallucinations","mdsupdrsyr8102hallucinations","mdsupdrsyr9102hallucinations","mdsupdrsyr10102hallucinations","mdsupdrsyr11102hallucinations",
         "updrsblitem2thoughtdisorders","updrsyr1item2thoughtdisorders","updrsyr2item2thoughtdisorders","updrsyr3item2thoughtdisorders","updrsyr4item2thoughtdisorders","updrsyr5item2thoughtdisorders","updrsyr6item2thoughtdisorders","updrsyr7item2thoughtdisorders","updrsyr8item2thoughtdisorders","updrsyr9item2thoughtdisorders","updrsyr10item2thoughtdisorders","updrsyr11item2thoughtdisorders")



data1.up$study<-factor(data1.up$study,
                    levels = c(1,2,3,4,5,6),
                    labels= c("CamPalGN","ICICLE","NYPUM","ParkWest","PICNICS","PINE"))
#remove ICICLE

data1.up<-data1.up%>%
  filter(study!="ICICLE")

data1.up$study<-droplevels(data1.up$study)
```

```{r update dementia data}

#Already check the update in updated dementia data.rmd file

#Here is to update the dementia data

#Update part: 
#1. read the data_update.csv (this is the data contains new dementia censoring date)
#2. replace the censoring data before t to enddatedementia
#3. used the enddatedementia as this is the new censoring date, while the defination of the censoring date don't need to change at all

censordate.update<-read.csv("data_update.csv") 

censordate.update<-censordate.update%>%
  select("idpicc","originalid","dementia","enddatedementia")

data1.up<-merge(data1.up,censordate.update, by= c("idpicc","originalid"),all.x = T) #x indicates the data1.up, merge by row

```



```{r pre data 2}
#----change into factor---

data1.up$sex<-factor(data1.up$sex,
                    levels = c(0,1),
                    labels= c("male","female"))


#UPDATE PCP46 and PCP66 both male

data1.up[data1.up$originalid=="PCP46",]$sex<-"male"
data1.up[data1.up$originalid=="PCP46",]$idpicc<-1692
data1.up[data1.up$originalid=="PCP66",]$sex<-"male"
data1.up[data1.up$originalid=="PCP66",]$idpicc<-1693


data1.up$smoking<-ifelse(data1.up$smoking<3,
                      1,2) #then 1 and 2 will be 1, 3 will be 2

data1.up$smoking<-factor(data1.up$smoking,
                      levels = c(1,2),
                      labels = c("yes","no"))


#------Create index for cognitive (yes/no)-------

#Cognitive symptoms as measured by UPDRS item 1 (intellectual impairment)/MDS-UPDRS item 1 (cognitive impairment), categorized as 0-1 (no cognitive symptoms), >1 (cognitive symptoms)

#Baseline

data1.up$mdsupdrsbl101cognitive[data1.up$mdsupdrsbl101cognitive>1]<-1     
data1.up$updrsblitem1intellectual[data1.up$updrsblitem1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitivebl=mdsupdrsbl101cognitive)%>%           
      mutate(cognitivebl=coalesce(cognitivebl,updrsblitem1intellectual))  # 0=no,1=yes

data1.up$cognitivebl<-factor(data1.up$cognitivebl,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))
#year 1

data1.up$mdsupdrsyr1101cognitive[data1.up$mdsupdrsyr1101cognitive>1]<-1     
data1.up$updrsyr1item1intellectual[data1.up$updrsyr1item1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitiveyr1=mdsupdrsyr1101cognitive)%>%           
      mutate(cognitiveyr1=coalesce(cognitiveyr1,updrsyr1item1intellectual))  # 0=no,1=yes

data1.up$cognitiveyr1<-factor(data1.up$cognitiveyr1,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#year 2

data1.up$mdsupdrsyr2101cognitive[data1.up$mdsupdrsyr2101cognitive>1]<-1     
data1.up$updrsyr2item1intellectual[data1.up$updrsyr2item1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitiveyr2=mdsupdrsyr2101cognitive)%>%           
      mutate(cognitiveyr2=coalesce(cognitiveyr2,updrsyr2item1intellectual))  # 0=no,1=yes

data1.up$cognitiveyr2<-factor(data1.up$cognitiveyr2,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))


#year 3

data1.up$mdsupdrsyr3101cognitive[data1.up$mdsupdrsyr3101cognitive>1]<-1     
data1.up$updrsyr3item1intellectual[data1.up$updrsyr3item1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitiveyr3=mdsupdrsyr3101cognitive)%>%           
      mutate(cognitiveyr3=coalesce(cognitiveyr3,updrsyr3item1intellectual))  # 0=no,1=yes

data1.up$cognitiveyr3<-factor(data1.up$cognitiveyr3,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#year 4

data1.up$mdsupdrsyr4101cognitive[data1.up$mdsupdrsyr4101cognitive>1]<-1     
data1.up$updrsyr4item1intellectual[data1.up$updrsyr4item1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitiveyr4=mdsupdrsyr4101cognitive)%>%           
      mutate(cognitiveyr4=coalesce(cognitiveyr4,updrsyr4item1intellectual))  # 0=no,1=yes

data1.up$cognitiveyr4<-factor(data1.up$cognitiveyr4,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))


#year 5

data1.up$mdsupdrsyr5101cognitive[data1.up$mdsupdrsyr5101cognitive>1]<-1     
data1.up$updrsyr5item1intellectual[data1.up$updrsyr5item1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitiveyr5=mdsupdrsyr5101cognitive)%>%           
      mutate(cognitiveyr5=coalesce(cognitiveyr5,updrsyr5item1intellectual))  # 0=no,1=yes

data1.up$cognitiveyr5<-factor(data1.up$cognitiveyr5,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#year 6

data1.up$mdsupdrsyr6101cognitive[data1.up$mdsupdrsyr6101cognitive>1]<-1     
data1.up$updrsyr6item1intellectual[data1.up$updrsyr6item1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitiveyr6=mdsupdrsyr6101cognitive)%>%           
      mutate(cognitiveyr6=coalesce(cognitiveyr6,updrsyr6item1intellectual))  # 0=no,1=yes

data1.up$cognitiveyr6<-factor(data1.up$cognitiveyr6,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#year 7

data1.up$mdsupdrsyr7101cognitive[data1.up$mdsupdrsyr7101cognitive>1]<-1     
data1.up$updrsyr7item1intellectual[data1.up$updrsyr7item1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitiveyr7=mdsupdrsyr7101cognitive)%>%           
      mutate(cognitiveyr7=coalesce(cognitiveyr7,updrsyr7item1intellectual))  # 0=no,1=yes

data1.up$cognitiveyr7<-factor(data1.up$cognitiveyr7,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#year 8

data1.up$mdsupdrsyr8101cognitive[data1.up$mdsupdrsyr8101cognitive>1]<-1     
data1.up$updrsyr8item1intellectual[data1.up$updrsyr8item1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitiveyr8=mdsupdrsyr8101cognitive)%>%           
      mutate(cognitiveyr8=coalesce(cognitiveyr8,updrsyr8item1intellectual))  # 0=no,1=yes

data1.up$cognitiveyr8<-factor(data1.up$cognitiveyr8,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#year 9

data1.up$mdsupdrsyr9101cognitive[data1.up$mdsupdrsyr9101cognitive>1]<-1     
data1.up$updrsyr9item1intellectual[data1.up$updrsyr9item1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitiveyr9=mdsupdrsyr9101cognitive)%>%           
      mutate(cognitiveyr9=coalesce(cognitiveyr9,updrsyr9item1intellectual))  # 0=no,1=yes

data1.up$cognitiveyr9<-factor(data1.up$cognitiveyr9,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#year 10

data1.up$mdsupdrsyr10101cognitive[data1.up$mdsupdrsyr10101cognitive>1]<-1     
data1.up$updrsyr10item1intellectual[data1.up$updrsyr10item1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitiveyr10=mdsupdrsyr10101cognitive)%>%           
      mutate(cognitiveyr10=coalesce(cognitiveyr10,updrsyr10item1intellectual))  # 0=no,1=yes

data1.up$cognitiveyr10<-factor(data1.up$cognitiveyr10,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#year 11

data1.up$mdsupdrsyr11101cognitive[data1.up$mdsupdrsyr11101cognitive>1]<-1     
data1.up$updrsyr11item1intellectual[data1.up$updrsyr11item1intellectual>1]<-1

data1.up<-data1.up %>%
      mutate(cognitiveyr11=mdsupdrsyr11101cognitive)%>%           
      mutate(cognitiveyr11=coalesce(cognitiveyr11,updrsyr11item1intellectual))  # 0=no,1=yes

data1.up$cognitiveyr11<-factor(data1.up$cognitiveyr11,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))



table(data1.up$cognitivebl,data1.up$study)
table(data1.up$cognitiveyr1,data1.up$study)
table(data1.up$cognitiveyr2,data1.up$study)
table(data1.up$cognitiveyr3,data1.up$study)
table(data1.up$cognitiveyr4,data1.up$study)
table(data1.up$cognitiveyr5,data1.up$study)
table(data1.up$cognitiveyr6,data1.up$study)
table(data1.up$cognitiveyr7,data1.up$study)
table(data1.up$cognitiveyr8,data1.up$study)
table(data1.up$cognitiveyr9,data1.up$study)
table(data1.up$cognitiveyr10,data1.up$study)
table(data1.up$cognitiveyr11,data1.up$study)


#------Create index for hallucinations------

#Baseline

data1.up$updrshallucinationsbl<-ifelse(data1.up$mdsupdrsbl102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersbl<-ifelse(data1.up$updrsblitem2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsbl=updrshallucinationsbl)%>%           
      mutate(hallucinationsbl=coalesce(hallucinationsbl,updrsthoughtdisordersbl)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsbl<-factor(data1.up$hallucinationsbl,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#Year 1

data1.up$updrshallucinationsyr1<-ifelse(data1.up$mdsupdrsyr1102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersyr1<-ifelse(data1.up$updrsyr1item2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsyr1=updrshallucinationsyr1)%>%           
      mutate(hallucinationsyr1=coalesce(hallucinationsyr1,updrsthoughtdisordersyr1)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsyr1<-factor(data1.up$hallucinationsyr1,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#Year 2

data1.up$updrshallucinationsyr2<-ifelse(data1.up$mdsupdrsyr2102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersyr2<-ifelse(data1.up$updrsyr2item2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsyr2=updrshallucinationsyr2)%>%           
      mutate(hallucinationsyr2=coalesce(hallucinationsyr2,updrsthoughtdisordersyr2)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsyr2<-factor(data1.up$hallucinationsyr2,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))


#Year 3

data1.up$updrshallucinationsyr3<-ifelse(data1.up$mdsupdrsyr3102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersyr3<-ifelse(data1.up$updrsyr3item2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsyr3=updrshallucinationsyr3)%>%           
      mutate(hallucinationsyr3=coalesce(hallucinationsyr3,updrsthoughtdisordersyr3)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsyr3<-factor(data1.up$hallucinationsyr3,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))


#Year 4

data1.up$updrshallucinationsyr4<-ifelse(data1.up$mdsupdrsyr4102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersyr4<-ifelse(data1.up$updrsyr4item2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsyr4=updrshallucinationsyr4)%>%           
      mutate(hallucinationsyr4=coalesce(hallucinationsyr4,updrsthoughtdisordersyr4)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsyr4<-factor(data1.up$hallucinationsyr4,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#Year 5

data1.up$updrshallucinationsyr5<-ifelse(data1.up$mdsupdrsyr5102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersyr5<-ifelse(data1.up$updrsyr5item2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsyr5=updrshallucinationsyr5)%>%           
      mutate(hallucinationsyr5=coalesce(hallucinationsyr5,updrsthoughtdisordersyr5)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsyr5<-factor(data1.up$hallucinationsyr5,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#Year 6

data1.up$updrshallucinationsyr6<-ifelse(data1.up$mdsupdrsyr6102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersyr6<-ifelse(data1.up$updrsyr6item2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsyr6=updrshallucinationsyr6)%>%           
      mutate(hallucinationsyr6=coalesce(hallucinationsyr6,updrsthoughtdisordersyr6)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsyr6<-factor(data1.up$hallucinationsyr6,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#Year 7

data1.up$updrshallucinationsyr7<-ifelse(data1.up$mdsupdrsyr7102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersyr7<-ifelse(data1.up$updrsyr7item2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsyr7=updrshallucinationsyr7)%>%           
      mutate(hallucinationsyr7=coalesce(hallucinationsyr7,updrsthoughtdisordersyr7)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsyr7<-factor(data1.up$hallucinationsyr7,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#Year 8

data1.up$updrshallucinationsyr8<-ifelse(data1.up$mdsupdrsyr8102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersyr8<-ifelse(data1.up$updrsyr8item2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsyr8=updrshallucinationsyr8)%>%           
      mutate(hallucinationsyr8=coalesce(hallucinationsyr8,updrsthoughtdisordersyr8)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsyr8<-factor(data1.up$hallucinationsyr8,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#Year 9

data1.up$updrshallucinationsyr9<-ifelse(data1.up$mdsupdrsyr9102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersyr9<-ifelse(data1.up$updrsyr9item2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsyr9=updrshallucinationsyr9)%>%           
      mutate(hallucinationsyr9=coalesce(hallucinationsyr9,updrsthoughtdisordersyr9)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsyr9<-factor(data1.up$hallucinationsyr9,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

#Year 10

data1.up$updrshallucinationsyr10<-ifelse(data1.up$mdsupdrsyr10102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersyr10<-ifelse(data1.up$updrsyr10item2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsyr10=updrshallucinationsyr10)%>%           
      mutate(hallucinationsyr10=coalesce(hallucinationsyr10,updrsthoughtdisordersyr10)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsyr10<-factor(data1.up$hallucinationsyr10,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))


#Year 11

data1.up$updrshallucinationsyr11<-ifelse(data1.up$mdsupdrsyr11102hallucinations>0,1,0)  # 1=yes,0=no

data1.up$updrsthoughtdisordersyr11<-ifelse(data1.up$updrsyr11item2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1.up<-data1.up %>%
      mutate(hallucinationsyr11=updrshallucinationsyr11)%>%           
      mutate(hallucinationsyr11=coalesce(hallucinationsyr11,updrsthoughtdisordersyr11)) #if updrshallucinations not find then use updrsthoughtdisorders

data1.up$hallucinationsyr11<-factor(data1.up$hallucinationsyr11,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))

table(data1.up$hallucinationsbl,data1.up$study)
table(data1.up$hallucinationsyr1,data1.up$study)
table(data1.up$hallucinationsyr2,data1.up$study)
table(data1.up$hallucinationsyr3,data1.up$study)
table(data1.up$hallucinationsyr4,data1.up$study)
table(data1.up$hallucinationsyr5,data1.up$study)
table(data1.up$hallucinationsyr6,data1.up$study)
table(data1.up$hallucinationsyr7,data1.up$study)
table(data1.up$hallucinationsyr8,data1.up$study)
table(data1.up$hallucinationsyr9,data1.up$study)
table(data1.up$hallucinationsyr10,data1.up$study)
table(data1.up$hallucinationsyr11,data1.up$study)

```


```{r not run cens events}

#-----Not run -------
#Below is the old code which is right, but the data got update, so don't need to run anymore
#create events/censoring years

#data1.up<-data1.up %>%
#  mutate(t=datedementia)%>%           
#  mutate(t=coalesce(t,datelastknownalive))%>%
#  mutate(t=coalesce(t,datelastseen))

#if patients have the date of dementia then t is the date of dementia. If patients without date of dementia, then the censoring date will be the date of last know alive. If patients without the date of last know alive then the censoring date will be the date last seen. Because I found some patients with date of lost is much later than the last seen, but the measurement stop in the last seen visiting year.

#data1.up$cens<-ifelse(is.na(data1.up$datedementia),0,1)  #0=right censored, 1=event 

#data1.up$tt<-as.Date(as.character(data1.up$t), format="%Y-%m-%d")-
#                as.Date(as.character(data1.up$datevisitbl), format="%Y-%m-%d")

#data1.up$tt<-as.numeric(data1.up$tt)

#data1.up$years<-data1.up$tt/365.25  

#Details of the reason of removing can be found in Dementia pre1.Rmd (the data only MMSE longtidinal)

#data1.up<-data1.up%>%
#  filter(data1.up$years>0) 

#data1.up%>%
#  group_by(study)%>%
#  count()

#data1.up%>%
#  group_by(study)%>%
# summarise(sum(cens))



#-----Run this new code----

data1.up$tt<-as.Date(as.character(data1.up$enddatedementia), format="%Y-%m-%d")-
                as.Date(as.character(data1.up$datevisitbl), format="%Y-%m-%d")

data1.up$tt<-as.numeric(data1.up$tt)

data1.up$years<-data1.up$tt/365.25

data1.up$cens<-data1.up$dementia #dementia is 1, censor is 0


#-----Details of the reason of removing----

data1.up%>%
  filter(tt==0)%>%
  group_by(study)%>%
  count(cens)            #cens=0 (only visit in baseline) CamPalGN 1 NYPUM 8 ParkWest 3 PICNICS 29 
                         #cens=1 (got dementia at baseline) ParkWest 1 PINE 4


data1.up[is.na(data1.up$years),] #One patients in PICNICS, originalid==PCP66, no censoring date, so have to remove


data1.up<-data1.up%>%
  filter(data1.up$years>0) #955 in total (exclude ICICLE already), now 908

#955-908=47

data1.up%>%
  group_by(study)%>%
  count() #908 


data1.up%>%
  group_by(study)%>%
  summarise(sum(cens))  #Still PINE should be the ref study as it had biggest event 


```

```{r up to 10 years}

#----up to 10 years----

data1.temp10.up<-survSplit(Surv(years, cens) ~ ., data = data1.up, cut = 10,
                  episode="timegroup")


data1.10.up<-subset(data1.temp10.up, timegroup == 1) #only the first 10 year

```

```{r KM plot}

KM<-survfit(Surv(years,cens)~study,data=data1.10.up)


ggsurv1<-ggsurvplot(KM,
           ylab="Cumulative probability of dementia",
           xlab="Time to dementia",
           legend="top",
           surv.median.line = "hv",
           fun="event",
           risk.table = T,
           risk.table.y.text.col = F,
           risk.table.y.text = T,
           risk.table.col = "strata",
           linetype = "strata",
           ggtheme = theme_bw(),
           legend.labs=c("CamPalGN","NYPUM","ParkWest","PICNICS","PINE"))

ggsurv1<-ggpar(ggsurv1, 
      font.main = c(14, "bold"),
      font.x = c(14, "bold"),
      font.y = c(14, "bold"),
      font.caption = c(14, "bold"), 
      font.legend = c(14, "bold"))

print(ggsurv1, 
      surv.plot.height = 0.6,
      risk.table.height = 0.4)


png("KM1.dementia.png",width = 4000,height =3000,res = 400)

print(ggsurv1, 
      surv.plot.height = 0.7,
      risk.table.height = 0.3)

dev.off()



```





```{r check missing data}
#impute data first before it change to longitudinal data

data.rename.up<-data1.10.up%>%  #rember to change to data1.10.remove
  rename("Age at baseline"=agebl, 
         "Sex"=sex,
         "MDS-UPDRS part3"=mdsupdrspart3bltotalconvertedasa,"Hoehn and Yahr Scale"=hybl, "Smoking"=smoking,
         "Years of education"=yearseducation
         ) #

explanatory<-c("Smoking","Years of education","MDS-UPDRS part3","Hoehn and Yahr Scale") 
dependent<- c("cens","tt") #"Smoking"

#png("missing.up.png",width = 3000,height =2000,res = 400)

mispattern.up<-data.rename.up %>% 
  missing_pattern(explanatory)

#dev.off()

#---check how many missing at least one---

colnames(data1.10.up[,c(8,9,10)])

nrow(data1.10.up[complete.cases(data1.10.up[,c(8,9,10)]),])  #854 in data1.10

(882-854)/882 #0.03

#Only 28 patient with missing value

#See how many patient with event have missing data

data1.10.up%>%
  filter(is.na(smoking))%>%
  count(cens)

#All missing mdsupdrs without event
#4 missing years of education had event
#3 missing smoking had event

#-----Impute missing data-----

#We impute the missing value with the impuation value of the second impuation dataset as in the previous analysis 
#Need to run the imputation first

data1.10.up%>%
  filter(is.na(smoking))

#Missing MDS-UPDRS idpicc 633 726 759 822 830 831 1246

#imp3.new%>%
#  filter(Imputation==2)%>%
#  filter(idpicc==1246)%>%
#  select(mdsupdrspart3bltotalconvertedasa)

data1.10.up[data1.10.up$idpicc==633,]$mdsupdrspart3bltotalconvertedasa<-9.177631	
data1.10.up[data1.10.up$idpicc==726,]$mdsupdrspart3bltotalconvertedasa<-18.94427
data1.10.up[data1.10.up$idpicc==759,]$mdsupdrspart3bltotalconvertedasa<-37.19017
data1.10.up[data1.10.up$idpicc==822,]$mdsupdrspart3bltotalconvertedasa<-64.63385
data1.10.up[data1.10.up$idpicc==830,]$mdsupdrspart3bltotalconvertedasa<-28.18615
data1.10.up[data1.10.up$idpicc==831,]$mdsupdrspart3bltotalconvertedasa<-28.70094
data1.10.up[data1.10.up$idpicc==1246,]$mdsupdrspart3bltotalconvertedasa<-50.15601	

#Missing years of education idpicc 10 48 90 111 324 329 350 384 1116 1118 1121 1143

#imp3.new%>%
#  filter(Imputation==2)%>%
#  filter(idpicc==329)%>%
#  select(yearseducation)

data1.10.up[data1.10.up$idpicc==10,]$yearseducation<-8.825283	
data1.10.up[data1.10.up$idpicc==48,]$yearseducation<-8.231928
data1.10.up[data1.10.up$idpicc==90,]$yearseducation<-11.89748		
data1.10.up[data1.10.up$idpicc==111,]$yearseducation<-10.35272		
data1.10.up[data1.10.up$idpicc==324,]$yearseducation<-13.94519	
data1.10.up[data1.10.up$idpicc==329,]$yearseducation<-19.00656	
data1.10.up[data1.10.up$idpicc==350,]$yearseducation<-6.584745	
data1.10.up[data1.10.up$idpicc==384,]$yearseducation<-9.084082		
data1.10.up[data1.10.up$idpicc==1116,]$yearseducation<-9.227734		
data1.10.up[data1.10.up$idpicc==1118,]$yearseducation<-11.02249			
data1.10.up[data1.10.up$idpicc==1121,]$yearseducation<-14.41573	
data1.10.up[data1.10.up$idpicc==1143,]$yearseducation<-5.652798		

#Missing smoking idpicc 637 662 680 683 686 717 737 810 847 

#imp3.new%>%
#  filter(Imputation==2)%>%
#  filter(idpicc==847)%>%
#  select(smoking)

#class(imp3.new$smoking)

data1.10.up[data1.10.up$idpicc==637,]$smoking<-"no"
data1.10.up[data1.10.up$idpicc==662,]$smoking<-"no"
data1.10.up[data1.10.up$idpicc==680,]$smoking<-"no"
data1.10.up[data1.10.up$idpicc==683,]$smoking<-"no"
data1.10.up[data1.10.up$idpicc==686,]$smoking<-"no"
data1.10.up[data1.10.up$idpicc==717,]$smoking<-"no"
data1.10.up[data1.10.up$idpicc==737,]$smoking<-"yes"
data1.10.up[data1.10.up$idpicc==810,]$smoking<-"no"
data1.10.up[data1.10.up$idpicc==847,]$smoking<-"no"


```


```{r change long format data}

#Now we have completed baseline variable in data1.10.up

#-----create follow-up times in years----


data1.10.up$year0<-0

data1.10.up$year1<-as.Date(as.character(data1.10.up$datevisityr1), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year1<-as.numeric(data1.10.up$year1)/365.25

data1.10.up$year2<-as.Date(as.character(data1.10.up$datevisityr2), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year2<-as.numeric(data1.10.up$year2)/365.25

data1.10.up$year3<-as.Date(as.character(data1.10.up$datevisityr3), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year3<-as.numeric(data1.10.up$year3)/365.25

data1.10.up$year4<-as.Date(as.character(data1.10.up$datevisityr4), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year4<-as.numeric(data1.10.up$year4)/365.25

data1.10.up$year5<-as.Date(as.character(data1.10.up$datevisityr5), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year5<-as.numeric(data1.10.up$year5)/365.25

data1.10.up$year6<-as.Date(as.character(data1.10.up$datevisityr6), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year6<-as.numeric(data1.10.up$year6)/365.25

data1.10.up$year7<-as.Date(as.character(data1.10.up$datevisityr7), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year7<-as.numeric(data1.10.up$year7)/365.25

data1.10.up$year8<-as.Date(as.character(data1.10.up$datevisityr8), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year8<-as.numeric(data1.10.up$year8)/365.25

data1.10.up$year9<-as.Date(as.character(data1.10.up$datevisityr9), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year9<-as.numeric(data1.10.up$year9)/365.25

data1.10.up$year10<-as.Date(as.character(data1.10.up$datevisityr10), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year10<-as.numeric(data1.10.up$year10)/365.25

data1.10.up$year11<-as.Date(as.character(data1.10.up$datevisityr11), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year11<-as.numeric(data1.10.up$year11)/365.25

data1.10.up$year12<-as.Date(as.character(data1.10.up$datevisityr12), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year12<-as.numeric(data1.10.up$year12)/365.25

data1.10.up$year13<-as.Date(as.character(data1.10.up$datevisityr13), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year13<-as.numeric(data1.10.up$year13)/365.25

data1.10.up$year14<-as.Date(as.character(data1.10.up$datevisityr14), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year14<-as.numeric(data1.10.up$year14)/365.25

data1.10.up$year15<-as.Date(as.character(data1.10.up$datevisityr15), format="%Y-%m-%d")-
                as.Date(as.character(data1.10.up$datevisitbl), format="%Y-%m-%d")
data1.10.up$year15<-as.numeric(data1.10.up$year15)/365.25


#----create year follow-up----

# Perform pivot_longer operation
years_long.up <- data1.10.up %>%
    pivot_longer(
      cols = c(`year0`:`year15`),
      names_to = "visityear",
      values_to = "followupyears",
      values_transform = ~ as.numeric(gsub(",", "", .x)),
      values_drop_na = TRUE
    )
  
years_long.up%>%
  select(study,idpicc,visityear,followupyears)


#----create MMSE follow-up----

# Select specific columns

MMSE_data.up <- data1.10.up %>%
    select("study", "idpicc", "originalid", "mmsebltotal",
           "mmseyr1total", "mmseyr2total", "mmseyr3total", "mmseyr4total",
           "mmseyr5total", "mmseyr6total", "mmseyr7total", "mmseyr8total",
           "mmseyr9total", "mmseyr10total", "mmseyr11total", "mmseyr12total")
  
# Rename selected columns

colnames(MMSE_data.up)[4:16] <- c("year0","year1", "year2", "year3", "year4",
                                 "year5", "year6", "year7", "year8",
                                 "year9", "year10", "year11", "year12")
  
# Perform pivot_longer operation
  mmse_long.up <- MMSE_data.up %>%
    pivot_longer(
      cols = `year0`:`year12`,
      names_to = "visityear",
      values_to = "mmse",
      values_transform = ~ as.numeric(gsub(",", "", .x)),
      values_drop_na = TRUE
    )
  

#----create cognitive symptoms follow-up----

cogni_data.up<-data1.10.up%>%
    select("study", "idpicc", "originalid","cognitivebl","cognitiveyr1","cognitiveyr2",
           "cognitiveyr3","cognitiveyr4","cognitiveyr5","cognitiveyr6","cognitiveyr7",
           "cognitiveyr8","cognitiveyr9","cognitiveyr10","cognitiveyr11")
  
# Rename selected columns

colnames(cogni_data.up)[4:15] <- c("year0","year1", "year2", "year3", "year4",
                                 "year5", "year6", "year7", "year8",
                                 "year9", "year10", "year11")
  
# Perform pivot_longer operation
  cogni_long.up <- cogni_data.up %>%
    pivot_longer(
      cols = `year0`:`year11`,
      names_to = "visityear",
      values_to = "cognitive",
      values_transform = ~ as.factor(gsub(",", "", .x)), #As it is factor, use as.factor
      values_drop_na = TRUE
    )

  
class(cogni_long.up$cognitive)


#----create hallucination follow-up----

hallucina_data.up<-data1.10.up%>%
    select("study", "idpicc", "originalid","hallucinationsbl","hallucinationsyr1","hallucinationsyr2",
           "hallucinationsyr3","hallucinationsyr4","hallucinationsyr5","hallucinationsyr6",
           "hallucinationsyr7","hallucinationsyr8","hallucinationsyr9","hallucinationsyr10","hallucinationsyr11")

# Rename selected columns

colnames(hallucina_data.up)[4:15] <- c("year0","year1", "year2", "year3", "year4",
                                 "year5", "year6", "year7", "year8",
                                 "year9", "year10", "year11")
  
# Perform pivot_longer operation
  hallucina_long.up <- hallucina_data.up %>%
    pivot_longer(
      cols = `year0`:`year11`,
      names_to = "visityear",
      values_to = "hallucination",
      values_transform = ~ as.factor(gsub(",", "", .x)), #As it is factor, use as.factor
      values_drop_na = TRUE
    )

class(hallucina_long.up$hallucination)
  
```

```{r combine long format}
nrow(years_long.up)  #5317
nrow(mmse_long.up)   #4618
nrow(cogni_long.up)  #5179
nrow(hallucina_long.up) #5187

years_long.up.new<-years_long.up%>%
  select("study","idpicc","originalid",
         "agebl","sex","hybl",
         "smoking","yearseducation","mdsupdrspart3bltotalconvertedasa",
         "cens","years","followupyears","visityear")


mmse_long.up.new<-mmse_long.up%>%
  select("study","idpicc","visityear","mmse")

data_long.up.1<-merge(years_long.up.new, mmse_long.up.new, by = c("study","idpicc","visityear"),all.x = T,all.y = T)

data_long.up.1<-data_long.up.1[order(data_long.up.1$id,data_long.up.1$visityear), ]

cogni_long.up.new<-cogni_long.up%>%
  select("study","idpicc","visityear","cognitive")

data_long.up.2<-merge(data_long.up.1,cogni_long.up.new, by= c("study","idpicc","visityear"),all.x = T,all.y = T)

data_long.up.2<-data_long.up.2[order(data_long.up.2$id,data_long.up.2$visityear), ]


hallucina_long.up.new<-hallucina_long.up%>%
  select("study","idpicc","visityear","hallucination")

data_long.up.3<-merge(data_long.up.2,hallucina_long.up.new, by= c("study","idpicc","visityear"),all.x = T,all.y = T)

data_long.up.3<-data_long.up.3[order(data_long.up.3$id,data_long.up.3$visityear), ]

```

```{r check missing data in long data}
#----check age----

data_long.up.3%>%
  group_by(study)%>%
  count(is.na(agebl))

#idpicc 1170 1235 1261 

#1170 The follow-up time is end in 10 years,patient has mmse value on 11 and 12 years. 
#1261 The follow-up time is end in 9 years, patient has mmse value on 10 and 11 years.

#remove value outside the last seen date

data_long.up.3<-data_long.up.3[!is.na(data_long.up.3$agebl), ]

#check sex

data_long.up.3%>%
  group_by(study)%>%
  count(is.na(sex))

```

```{r remove data after event}

#All follow-up records after event need to be removed

data_long.up.3.new<-data_long.up.3%>%
                  filter(years>followupyears)

```

```{r create baseline data}

data.baseline.up<-data1.10.up%>%
  select("study","idpicc","originalid","agebl","sex","hybl","mdsupdrspart3bltotalconvertedasa","yearseducation","smoking","hallucinationsbl",
         "cens","years")



levels(data_long.up.3.new$study)
levels(data.baseline.up$study)

setdiff(unique(data.baseline.up$idpicc),unique(data_long.up.3.new$idpicc)) #No different between this two study

```

```{r pre data for fit model}

data_long.fit.up<-data_long.up.3.new[complete.cases(data_long.up.3.new),]
  
data.baseline.fit.up<-data.baseline.up

diff_idpicc.up<-setdiff(unique(data.baseline.fit.up$idpicc),unique(data_long.fit.up$idpicc))

#idpicc 328 331 354 436 832 1169 1208 1271

data1.10.up%>%
  filter(idpicc %in% diff_idpicc.up)%>%
  group_by(study)%>%
  count()

#4 in NYPUM no MMSE at all 
#1 in PICNICS, no cognitive at all, the last seen is the same as baseline visit
#3 in PINE, one patient's last seen date is the same as baseline visit. One only had hallucination and cognitive records after dementia (so cannot use the information); one didn't have cognitive at all. 


data1.10.up%>%
  filter(idpicc %in% diff_idpicc.up)%>%
  filter(study=="PINE")

data_long.up.3.new%>%
  filter(idpicc==1208)

data1.10.up%>%
  filter(idpicc==1208)%>%
  select(cognitivebl)

data.baseline.fit.up<-data.baseline.fit.up%>%
  filter(!idpicc %in% diff_idpicc.up)

#874 in total
#The baseline characteristic need to change again. 

#----change PINE to reference level----

data.baseline.fit.up$study<-factor(data.baseline.fit.up$study,levels=c("PINE","CamPalGN","NYPUM","ParkWest","PICNICS")) #put PINE as the first level

levels(data.baseline.fit.up$study)

data.baseline.fit.up%>%
  group_by(study)%>%
  summarise(sum(cens))

```

```{r linear mixed models}

data_long.fit.up$study<-factor(data_long.fit.up$study,levels=c("PINE","CamPalGN","NYPUM","ParkWest","PICNICS")) #put PINE as the first level

levels(data_long.fit.up$study)



#---For MMSE----

lme.up<-lme(mmse~ study+agebl+sex+yearseducation, random = ~ followupyears | idpicc, data=data_long.fit.up)


#---For cognitive symptom----

lme.cog1<-mixed_model(cognitive~study+agebl+sex,random = ~ followupyears | idpicc, data=data_long.fit.up,family = binomial() )

lme.cog2<-mixed_model(cognitive~study+agebl+sex+yearseducation,random = ~ followupyears | idpicc, data=data_long.fit.up,family = binomial() )

lme.cog3<-mixed_model(cognitive~study+agebl+sex+yearseducation+mdsupdrspart3bltotalconvertedasa,random = ~ followupyears | idpicc, data=data_long.fit.up,family = binomial() )

AIC(lme.cog1) #4276.5
AIC(lme.cog2) #4271.8
AIC(lme.cog3) #4253.7

BIC(lme.cog1) #4324.2
BIC(lme.cog2) #4324.3
BIC(lme.cog3) #4311.0

#Choose between lme.cog2 and lme.cog3, after compare jm, it's lme.cog2


#-----For hallucination----


lme.hall1<-mixed_model(hallucination~study+agebl+sex,random = ~ followupyears | idpicc, data=data_long.fit.up,family = binomial() )

lme.hall2<-mixed_model(hallucination~study+agebl+sex+yearseducation,random = ~ followupyears | idpicc, data=data_long.fit.up,family = binomial() )

lme.hall3<-mixed_model(hallucination~study+agebl+sex+yearseducation+smoking,random = ~ followupyears | idpicc, data=data_long.fit.up,family = binomial() )

AIC(lme.hall1) #1924.1
AIC(lme.hall2) #1925.7
AIC(lme.hall3) #1925.4

BIC(lme.hall1) #1971.8
BIC(lme.hall2) #1978.2
BIC(lme.hall3) #1982.7

#Choose lme.hall1


```


```{r Cox model}

#Because Adding hallucination cannot convergence, we learnt that from JM, so put hallucination in baseline instead

#So I need to impute the missing hallucinationsbl from the mutiple imputation datatset 2 first

#idpicc_nahall<-data.baseline.fit.up[is.na(data.baseline.fit.up$hallucinationsbl),]$idpicc

#need to run the imputation first

#impute_nahall<-data.imp2[data.imp2$idpicc%in%idpicc_nahall,]$hallucinationsindex

#factor, no  no  no  no  no  no  no  no  no  no  no  yes no  no  no  no  no  no  no  no  no  no  no  no  no  no  no  no  yes

#data.baseline.fit.up[data.baseline.fit.up$idpicc %in% idpicc_nahall,]$hallucinationsbl<-impute_nahall


#----try to add hallunciation in Cox, but all JM are not convergent---

#----so remove hallunciation from Cox----

baseline.cox.up1<-coxph(Surv(years,cens)~agebl+sex+yearseducation+mdsupdrspart3bltotalconvertedasa+hybl+study,data=data.baseline.fit.up, x = TRUE,model = TRUE) #without smoking

baseline.cox.up2<-coxph(Surv(years,cens)~agebl+sex+yearseducation+mdsupdrspart3bltotalconvertedasa+hybl+study+smoking,data=data.baseline.fit.up, x = TRUE,model = TRUE) #with smoking

```


```{r joint model}

#Save all the fitted mixed-effects model in a list

#Adding hallucination cannot convergence 

#Move hallucination out

Mixed1<-list(lme.up,lme.cog2) #lme.hall1
Mixed2<-list(lme.up,lme.cog3) #Chose one


jointFit.up1<-jm(baseline.cox.up1,Mixed_objects = Mixed1,time_var = "followupyears") #JM1

jointFit.up3<-jm(baseline.cox.up2,Mixed_objects = Mixed1,time_var = "followupyears") #JM2

jointFit.up4<-jm(baseline.cox.up1,Mixed_objects = Mixed2,time_var = "followupyears") #JM3

jointFit.up2<-jm(baseline.cox.up2,Mixed_objects = Mixed2,time_var = "followupyears") #JM4





compare_jm(jointFit.up1,jointFit.up2,jointFit.up3,jointFit.up4)

summary(jointFit.up1)
summary(jointFit.up2)
summary(jointFit.up3)
summary(jointFit.up4)

#when choosing lme.cog2
#jointFit.up1 DIC 20400.82   WAIC  20512.61
#jointFit.up2 DIC 20431.28   WAIC  20532.89
#choose jointFit.up1 (baseline.cox.up1)
#Don't need smoking

#When choosing lme.cog3
#jointFit.up2 DIC 20466.74   WAIC  20532.97
#jointFit.up1 DIC 20406.40   WAIC  20568.29 #don't cogervence in mmse
#choose jointFit.up2

#Choose between 
#baseline.cox.up1+lme.cog2 DIC 20400.82   WAIC  20512.61 
#Rhat in mmse is 1.2, in cognitive is 1.1

#baseline.cox.up2+lme.cog3 DIC 20466.74   WAIC  20532.97
#Rhat in mmse is 1.00, in cognitive is 1.01

#Looks like jointFit.up2 (baseline.cox.up2+lme.cog3) is better

summary(jointFit.up2)
```

```{r predict 1131}

#randomly select patient as example to illustrate

predict.data<-data_long.fit.up[data_long.fit.up$idpicc == 1131,]  #idpicc 1131 event year is 6

#----Only baseline information-----

predict.data.time.0<-predict.data[predict.data$followupyears==0,] 

predict.data.time.0$cens<-0 #not event

predict.data.time.0$years<-0 #predict time at 0 years

predLong.0<-predict(jointFit.up2,newdata = predict.data.time.0,times = seq(0,3, length.out=20),return_newdata = T) #for future time point

predSurv.0<-predict(jointFit.up2,newdata = predict.data.time.0,process = "event",times = seq(0,3, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predLong.0,predSurv.0,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"))


#-----From baseline up to 1 year-----

predict.data.time.1<-predict.data[predict.data$followupyears<2,] 

predict.data.time.1$cens<-0 #not event

predict.data.time.1$years<-1.2 

predLong.1<-predict(jointFit.up2,newdata = predict.data.time.1,times = seq(1.2,4, length.out=20),return_newdata = T) #for future time point

predSurv.1<-predict(jointFit.up2,newdata = predict.data.time.1,process = "event",times = seq(1.2,4, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predLong.1,predSurv.1,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"))


#-----From baseline up to 2 year-----

predict.data.time.2<-predict.data[predict.data$followupyears<3,] 

predict.data.time.2$cens<-0 #not event

predict.data.time.2$years<-2.1 

predLong.2<-predict(jointFit.up2,newdata = predict.data.time.2,times = seq(2.1,5, length.out=20),return_newdata = T) #for future time point

predSurv.2<-predict(jointFit.up2,newdata = predict.data.time.2,process = "event",times = seq(2.1,5, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predLong.2,predSurv.2,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"))



#------From baseline up to 3 years-----

predict.data.time.3<-predict.data[predict.data$followupyears<4,] 

predict.data.time.3$cens<-0 #not event

predict.data.time.3$years<-3.1 

#predict for longitudinal outcomes

predLong.3<-predict(jointFit.up2,newdata = predict.data.time.3,times = seq(3.1,6, length.out=20),return_newdata = T) #for future time point

predSurv.3<-predict(jointFit.up2,newdata = predict.data.time.3,process = "event",times = seq(3.1,6, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predLong.3,predSurv.3,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"))


#------From baseline up to 4 years-----

predict.data.time.4<-predict.data[predict.data$followupyears<5,] 

predict.data.time.4$cens<-0 #not event

predict.data.time.4$years<-4 

#predict for longitudinal outcomes

predLong.4<-predict(jointFit.up2,newdata = predict.data.time.4,times = seq(4,7, length.out=20),return_newdata = T) #for future time point

predSurv.4<-predict(jointFit.up2,newdata = predict.data.time.4,process = "event",times = seq(4,7, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predLong.4,predSurv.4,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"))


#------From baseline up to 5 years-----

predict.data.time.5<-predict.data[predict.data$followupyears<6,] 

predict.data.time.5$cens<-0 #not event

predict.data.time.5$years<-5.04 

#predict for longitudinal outcomes

predLong.5<-predict(jointFit.up2,newdata = predict.data.time.5,times = seq(5.04,8, length.out=20),return_newdata = T) #for future time point

predSurv.5<-predict(jointFit.up2,newdata = predict.data.time.5,process = "event",times = seq(5.04,8, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predLong.5,predSurv.5,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"))


#----Arrange plot----

png("JMpred.PINE0.png",width = 2000,height =2500,res = 400)

plot(predLong.0,predSurv.0,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)

dev.off()

png("JMpred.PINE1.png",width = 2000,height =2500,res = 400)
plot(predLong.1,predSurv.1,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()

png("JMpred.PINE2.png",width = 2000,height =2500,res = 400)
plot(predLong.2,predSurv.2,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()

png("JMpred.PINE3.png",width = 2000,height =2500,res = 400)
plot(predLong.3,predSurv.3,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()

png("JMpred.PINE4.png",width = 2000,height =2500,res = 400)
plot(predLong.4,predSurv.4,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()

png("JMpred.PINE5.png",width = 2000,height =2500,res = 400)
plot(predLong.5,predSurv.5,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()

```

```{r predict 79}

#randomly select patient as example to illustrate

predict.data<-data_long.fit.up[data_long.fit.up$idpicc == 79,]  #idpicc 14 event year is 7

#----Only baseline information-----

predict.data.time.0<-predict.data[predict.data$followupyears==0,] 

predict.data.time.0$cens<-0 #not event

predict.data.time.0$years<-0 #predict time at 0 years

predLong.0<-predict(jointFit.up2,newdata = predict.data.time.0,times = seq(0,3, length.out=20),return_newdata = T) #for future time point

predSurv.0<-predict(jointFit.up2,newdata = predict.data.time.0,process = "event",times = seq(0,3, length.out=20),return_newdata = T) # use the information before 3 years to predict

png("JMpred.Cam0.png",width = 2000,height =2500,res = 400)
plot(predLong.0,predSurv.0,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()


#-----From baseline up to 3 year-----

predict.data.time.2<-predict.data[predict.data$followupyears<4,] 

predict.data.time.2$cens<-0 #not event

predict.data.time.2$years<-3 

predLong.2<-predict(jointFit.up2,newdata = predict.data.time.2,times = seq(3,6, length.out=20),return_newdata = T) #for future time point

predSurv.2<-predict(jointFit.up2,newdata = predict.data.time.2,process = "event",times = seq(3,6, length.out=20),return_newdata = T) # use the information before 3 years to predict

png("JMpred.Cam2.png",width = 2000,height =2500,res = 400)
plot(predLong.2,predSurv.2,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()

#------From baseline up to 5 years-----

predict.data.time.4<-predict.data[predict.data$followupyears<5,] 

predict.data.time.4$cens<-0 #not event

predict.data.time.4$years<-4.9 

#predict for longitudinal outcomes

predLong.4<-predict(jointFit.up2,newdata = predict.data.time.4,times = seq(4.9,7.9, length.out=20),return_newdata = T) #for future time point

predSurv.4<-predict(jointFit.up2,newdata = predict.data.time.4,process = "event",times = seq(4.9,7.9, length.out=20),return_newdata = T) # use the information before 3 years to predict

png("JMpred.Cam4.png",width = 2000,height =2500,res = 400)
plot(predLong.4,predSurv.4,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()

#------From baseline up to 7 years-----

predict.data.time.5<-predict.data[predict.data$followupyears<7,] 

predict.data.time.5$cens<-0 #not event

predict.data.time.5$years<-6.8

#predict for longitudinal outcomes

predLong.5<-predict(jointFit.up2,newdata = predict.data.time.5,times = seq(6.8,9.8, length.out=20),return_newdata = T) #for future time point

predSurv.5<-predict(jointFit.up2,newdata = predict.data.time.5,process = "event",times = seq(6.8,9.8, length.out=20),return_newdata = T) # use the information before 3 years to predict

png("JMpred.Cam5.png",width = 2000,height =2500,res = 400)
plot(predLong.5,predSurv.5,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()


```


```{r predict 348}

#randomly select patient as example to illustrate

predict.data<-data_long.fit.up[data_long.fit.up$idpicc == 348,]  #idpicc 1131 event year is 9

#----Only baseline information-----

predict.data.time.0<-predict.data[predict.data$followupyears==0,] 

predict.data.time.0$cens<-0 #not event

predict.data.time.0$years<-0 #predict time at 0 years

predLong.0<-predict(jointFit.up2,newdata = predict.data.time.0,times = seq(0,3, length.out=20),return_newdata = T) #for future time point

predSurv.0<-predict(jointFit.up2,newdata = predict.data.time.0,process = "event",times = seq(0,3, length.out=20),return_newdata = T) # use the information before 3 years to predict


png("JMpred.NY0.png",width = 2000,height =3000,res = 400)
plot(predLong.0,predSurv.0,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()


#-----From baseline up to 1 year-----

predict.data.time.1<-predict.data[predict.data$followupyears<2,] 

predict.data.time.1$cens<-0 #not event

predict.data.time.1$years<-1 

predLong.1<-predict(jointFit.up2,newdata = predict.data.time.1,times = seq(1,4, length.out=20),return_newdata = T) #for future time point

predSurv.1<-predict(jointFit.up2,newdata = predict.data.time.1,process = "event",times = seq(1,4, length.out=20),return_newdata = T) # use the information before 3 years to predict


png("JMpred.NY1.png",width = 2000,height =3000,res = 400)
plot(predLong.1,predSurv.1,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()


#-----From baseline up to 2 year-----

predict.data.time.2<-predict.data[predict.data$followupyears<3,] 

predict.data.time.2$cens<-0 #not event

predict.data.time.2$years<-2 

predLong.2<-predict(jointFit.up2,newdata = predict.data.time.2,times = seq(2,5, length.out=20),return_newdata = T) #for future time point

predSurv.2<-predict(jointFit.up2,newdata = predict.data.time.2,process = "event",times = seq(2,5, length.out=20),return_newdata = T) # use the information before 3 years to predict


png("JMpred.NY2.png",width = 2000,height =3000,res = 400)
plot(predLong.2,predSurv.2,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()




#------From baseline up to 3 years-----

predict.data.time.3<-predict.data[predict.data$followupyears<4,] 

predict.data.time.3$cens<-0 #not event

predict.data.time.3$years<-3.04 

#predict for longitudinal outcomes

predLong.3<-predict(jointFit.up2,newdata = predict.data.time.3,times = seq(3.04,6, length.out=20),return_newdata = T) #for future time point

predSurv.3<-predict(jointFit.up2,newdata = predict.data.time.3,process = "event",times = seq(3.04,6, length.out=20),return_newdata = T) # use the information before 3 years to predict

png("JMpred.NY3.png",width = 2000,height =3000,res = 400)
plot(predLong.3,predSurv.3,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()



#------From baseline up to 4 years-----

predict.data.time.4<-predict.data[predict.data$followupyears<5,] 

predict.data.time.4$cens<-0 #not event

predict.data.time.4$years<-4.1 

#predict for longitudinal outcomes

predLong.4<-predict(jointFit.up2,newdata = predict.data.time.4,times = seq(4.1,7, length.out=20),return_newdata = T) #for future time point

predSurv.4<-predict(jointFit.up2,newdata = predict.data.time.4,process = "event",times = seq(4.1,7, length.out=20),return_newdata = T) # use the information before 3 years to predict

png("JMpred.NY4.png",width = 2000,height =3000,res = 400)
plot(predLong.4,predSurv.4,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()



#------From baseline up to 5 years-----

predict.data.time.5<-predict.data[predict.data$followupyears<6,] 

predict.data.time.5$cens<-0 #not event

predict.data.time.5$years<-5.04 

#predict for longitudinal outcomes

predLong.5<-predict(jointFit.up2,newdata = predict.data.time.5,times = seq(5.04,8, length.out=20),return_newdata = T) #for future time point

predSurv.5<-predict(jointFit.up2,newdata = predict.data.time.5,process = "event",times = seq(5.04,8, length.out=20),return_newdata = T) # use the information before 3 years to predict

png("JMpred.NY5.png",width = 2000,height =3000,res = 400)
plot(predLong.5,predSurv.5,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()


#------From baseline up to 6 years-----

predict.data.time.6<-predict.data[predict.data$followupyears<7,] 

predict.data.time.6$cens<-0 #not event

predict.data.time.6$years<-6.04 

#predict for longitudinal outcomes

predLong.6<-predict(jointFit.up2,newdata = predict.data.time.6,times = seq(6.04,9, length.out=20),return_newdata = T) #for future time point

predSurv.6<-predict(jointFit.up2,newdata = predict.data.time.6,process = "event",times = seq(6.04,9, length.out=20),return_newdata = T) # use the information before 3 years to predict

png("JMpred.NY6.png",width = 2000,height =3000,res = 400)
plot(predLong.6,predSurv.6,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()


#------From baseline up to 8 years-----

predict.data.time.8<-predict.data[predict.data$followupyears<8,] 

predict.data.time.8$cens<-0 #not event

predict.data.time.8$years<-8 

#predict for longitudinal outcomes

predLong.8<-predict(jointFit.up2,newdata = predict.data.time.8,times = seq(8,10, length.out=20),return_newdata = T) #for future time point

predSurv.8<-predict(jointFit.up2,newdata = predict.data.time.8,process = "event",times = seq(8,10, length.out=20),return_newdata = T) 

png("JMpred.NY8.png",width = 2000,height =3000,res = 400)
plot(predLong.8,predSurv.8,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()



```


```{r predict 492}

#randomly select patient as example to illustrate

predict.data<-data_long.fit.up[data_long.fit.up$idpicc == 492,]  #idpicc 1131 event year is 9

#----Only baseline information-----

predict.data.time.0<-predict.data[predict.data$followupyears==0,] 

predict.data.time.0$cens<-0 #not event

predict.data.time.0$years<-0 #predict time at 0 years

predLong.0<-predict(jointFit.up2,newdata = predict.data.time.0,times = seq(0,3, length.out=20),return_newdata = T) #for future time point

predSurv.0<-predict(jointFit.up2,newdata = predict.data.time.0,process = "event",times = seq(0,3, length.out=20),return_newdata = T) # use the information before 3 years to predict

png("JMpred.PA0.png",width = 2000,height =3000,res = 400)
plot(predLong.0,predSurv.0,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()

#-----From baseline up to 1 year-----

predict.data.time.1<-predict.data[predict.data$followupyears<2,] 

predict.data.time.1$cens<-0 #not event

predict.data.time.1$years<-1 

predLong.1<-predict(jointFit.up2,newdata = predict.data.time.1,times = seq(1,4, length.out=20),return_newdata = T) #for future time point

predSurv.1<-predict(jointFit.up2,newdata = predict.data.time.1,process = "event",times = seq(1,4, length.out=20),return_newdata = T) # use the information before 3 years to predict


png("JMpred.PA1.png",width = 2000,height =3000,res = 400)
plot(predLong.1,predSurv.1,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()


#-----From baseline up to 3 year-----

predict.data.time.2<-predict.data[predict.data$followupyears<3,] 

predict.data.time.2$cens<-0 #not event

predict.data.time.2$years<-3 

predLong.2<-predict(jointFit.up2,newdata = predict.data.time.2,times = seq(3,6, length.out=20),return_newdata = T) #for future time point

predSurv.2<-predict(jointFit.up2,newdata = predict.data.time.2,process = "event",times = seq(3,6, length.out=20),return_newdata = T) # use the information before 3 years to predict


png("JMpred.PA2.png",width = 2000,height =3000,res = 400)
plot(predLong.2,predSurv.2,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()


#------From baseline up to 5 years-----

predict.data.time.5<-predict.data[predict.data$followupyears<6,] 

predict.data.time.5$cens<-0 #not event

predict.data.time.5$years<-5 

#predict for longitudinal outcomes

predLong.5<-predict(jointFit.up2,newdata = predict.data.time.5,times = seq(5,8, length.out=20),return_newdata = T) #for future time point

predSurv.5<-predict(jointFit.up2,newdata = predict.data.time.5,process = "event",times = seq(5,8, length.out=20),return_newdata = T) # use the information before 3 years to predict


png("JMpred.PA5.png",width = 2000,height =3000,res = 400)
plot(predLong.5,predSurv.5,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()


```


```{r predict 885}

#randomly select patient as example to illustrate

predict.data<-data_long.fit.up[data_long.fit.up$idpicc == 885,]  #idpicc 885 event year is 6

#----Only baseline information-----

predict.data.time.0<-predict.data[predict.data$followupyears==0,] 

predict.data.time.0$cens<-0 #not event

predict.data.time.0$years<-0 #predict time at 0 years

predLong.0<-predict(jointFit.up2,newdata = predict.data.time.0,times = seq(0,3, length.out=20),return_newdata = T) #for future time point

predSurv.0<-predict(jointFit.up2,newdata = predict.data.time.0,process = "event",times = seq(0,3, length.out=20),return_newdata = T) # use the information before 3 years to predict


png("JMpred.PIC0.png",width = 2000,height =3000,res = 400)
plot(predLong.0,predSurv.0,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()

#-----From baseline up to 3 year-----

predict.data.time.2<-predict.data[predict.data$followupyears<3,] 

predict.data.time.2$cens<-0 #not event

predict.data.time.2$years<-2.4 

predLong.2<-predict(jointFit.up2,newdata = predict.data.time.2,times = seq(2.4,5, length.out=20),return_newdata = T) #for future time point

predSurv.2<-predict(jointFit.up2,newdata = predict.data.time.2,process = "event",times = seq(2.4,5, length.out=20),return_newdata = T) # use the information before 3 years to predict


png("JMpred.PIC2.png",width = 2000,height =3000,res = 400)
plot(predLong.2,predSurv.2,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()



#------From baseline up to 4 years-----

predict.data.time.4<-predict.data[predict.data$followupyears<4,] 

predict.data.time.4$cens<-0 #not event

predict.data.time.4$years<-3.9 

#predict for longitudinal outcomes

predLong.4<-predict(jointFit.up2,newdata = predict.data.time.4,times = seq(3.9,7, length.out=20),return_newdata = T) #for future time point

predSurv.4<-predict(jointFit.up2,newdata = predict.data.time.4,process = "event",times = seq(3.9,7, length.out=20),return_newdata = T) # use the information before 3 years to predict

png("JMpred.PIC4.png",width = 2000,height =3000,res = 400)
plot(predLong.4,predSurv.4,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()


#------From baseline up to 5 years-----

predict.data.time.5<-predict.data[predict.data$followupyears<6,] 

predict.data.time.5$cens<-0 #not event

predict.data.time.5$years<-5.5 

#predict for longitudinal outcomes

predLong.5<-predict(jointFit.up2,newdata = predict.data.time.5,times = seq(5.5,8.5, length.out=20),return_newdata = T) #for future time point

predSurv.5<-predict(jointFit.up2,newdata = predict.data.time.5,process = "event",times = seq(5.5,8.5, length.out=20),return_newdata = T) # use the information before 3 years to predict

png("JMpred.PIC5.png",width = 2000,height =3000,res = 400)
plot(predLong.5,predSurv.5,outcomes=1:2,
     ylab_event="Cumulative risk of dementia",
     ylab_long=c("cognitive symptom","MMSE"),
     xlab = "Follow-up years",cex_ylab_long = 1.5,cex_axis = 1.2,cex_xlab = 1)
dev.off()




```


```{r IECV outline Cam}

#Leave the CamPalGN study out as external validation

#So the development model will be based on PINE NYPUM PICNICS ParKwest

#And the validation dataset will be CamPalGN. Therefore, we need to decide which study looks most simliar to CamPalGN and use this study fixed effect to refit the CamPalGN study. From the KM curves, I think NYPUM has the most similar patter. And looking at the baseline characteristics, either NYPUM or PINE. For incidence rate is closer to NYPUM. 

#Hence I chose NYPUM 

```

```{r IECV Cam}

#---development dataset---

IECV_devlong_1<-data_long.fit.up%>%
  filter(study!="CamPalGN")

IECV_devbase_1<-data.baseline.fit.up%>%
  filter(study!="CamPalGN")

IECV_devlong_1$study<-droplevels(IECV_devlong_1$study)
IECV_devbase_1$study<-droplevels(IECV_devbase_1$study)


#----validation dataset---

IECV_vlong_1<-data_long.fit.up%>%
  filter(study=="CamPalGN")

IECV_vbase_1<-data.baseline.fit.up%>%
  filter(study=="CamPalGN")

IECV_vlong_1$study<-droplevels(IECV_vlong_1$study)
IECV_vbase_1$study<-droplevels(IECV_vbase_1$study)


#----development model----

mmse.dev1<-lme(mmse~ study+agebl+sex+yearseducation, random = ~ followupyears | idpicc, data=IECV_devlong_1)

cog.dev1<-mixed_model(cognitive~study+agebl+sex+yearseducation+mdsupdrspart3bltotalconvertedasa,random = ~ followupyears | idpicc, data=IECV_devlong_1,family = binomial() )

Mixed_dev1<-list(mmse.dev1,cog.dev1)

Cox_dev1<-coxph(Surv(years,cens)~agebl+sex+yearseducation+mdsupdrspart3bltotalconvertedasa+hybl+study+smoking,data=IECV_devbase_1, x = TRUE,model = TRUE)


jm_dev1<-jm(Cox_dev1,Mixed_objects = Mixed_dev1,time_var = "followupyears") 

#summary(jm_dev1)

#----validate in the CamPalGN---

#Change the study to NYPUM

levels(IECV_devlong_1$study)

levels(IECV_vlong_1$study)<-c("NYPUM","PINE","ParkWest","PICNICS") #Only take NYPUM levels, other levels won't be used

roc.Cam.0<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 0,Dt=3,cores=1L)
roc.Cam.1<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 1,Dt=3,cores=1L)
roc.Cam.2<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 2,Dt=3,cores=1L)
roc.Cam.3<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 3,Dt=3,cores=1L)
roc.Cam.4<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 4,Dt=3,cores=1L)
roc.Cam.5<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 5,Dt=3,cores=1L)
roc.Cam.6<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 6,Dt=3,cores=1L)


tvAUC(roc.Cam.0)
tvAUC(roc.Cam.1)
tvAUC(roc.Cam.2)
tvAUC(roc.Cam.3)
tvAUC(roc.Cam.4)
tvAUC(roc.Cam.5)
tvAUC(roc.Cam.6)


calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 3,Dt=3,plot = TRUE)
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 4,Dt=3,plot = TRUE)
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 5,Dt=3,plot = TRUE)
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 6,Dt=3,plot = TRUE)




```


```{r IECV Parkwest}

#---development dataset---

IECV_devlong_3<-data_long.fit.up%>%
  filter(study!="ParkWest")

IECV_devbase_3<-data.baseline.fit.up%>%
  filter(study!="ParkWest")

IECV_devlong_3$study<-droplevels(IECV_devlong_3$study)
IECV_devbase_3$study<-droplevels(IECV_devbase_3$study)

#----validation dataset---

IECV_vlong_3<-data_long.fit.up%>%
  filter(study=="ParkWest")

IECV_vlong_3$study<-droplevels(IECV_vlong_3$study)

#----development model----

mmse.dev3<-lme(mmse~ study+agebl+sex+yearseducation, random = ~ followupyears | idpicc, data=IECV_devlong_3)

cog.dev3<-mixed_model(cognitive~study+agebl+sex+yearseducation+mdsupdrspart3bltotalconvertedasa,random = ~ followupyears | idpicc, data=IECV_devlong_3,family = binomial() )

Mixed_dev3<-list(mmse.dev3,cog.dev3)

Cox_dev3<-coxph(Surv(years,cens)~agebl+sex+yearseducation+mdsupdrspart3bltotalconvertedasa+hybl+study+smoking,data=IECV_devbase_3, x = TRUE,model = TRUE)


jm_dev3<-jm(Cox_dev3,Mixed_objects = Mixed_dev3,time_var = "followupyears") 

summary(jm_dev3)

#----validate in the ParkWest---

#Change the study to NYPUM

levels(IECV_vlong_3$study)

levels(IECV_vlong_3$study)<-c("PICNICS","NYPUM","PINE","CamPalGN") #Only take PICNICS levels, other levels won't be used

roc.PA.0<-tvROC(jm_dev3,newdata=IECV_vlong_3,Tstart = 0,Dt=3,cores=1L)
roc.PA.1<-tvROC(jm_dev3,newdata=IECV_vlong_3,Tstart = 1,Dt=3,cores=1L)
roc.PA.2<-tvROC(jm_dev3,newdata=IECV_vlong_3,Tstart = 2,Dt=3,cores=1L)
roc.PA.3<-tvROC(jm_dev3,newdata=IECV_vlong_3,Tstart = 3,Dt=3,cores=1L)

tvAUC(roc.PA.0)
tvAUC(roc.PA.1)
tvAUC(roc.PA.2)
tvAUC(roc.PA.3)

calibration_plot(jm_dev3,newdata = IECV_vlong_3,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_dev3,newdata = IECV_vlong_3,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_dev3,newdata = IECV_vlong_3,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_dev3,newdata = IECV_vlong_3,Tstart = 3,Dt=3,plot = TRUE)
```