---
title: "Dementia pre 1"
output: html_document
date: "2023-05-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(dplyr)
library(tidyr)
library(Hmisc)
library(finalfit)
library(jomo)
library(mice)
library(mitools)
library(rms)
library(mitml)
library(survminer)
library(patchwork) #Arrange plot
library(ggplot2)
library(GGally)
library(gridExtra)
library(png)
library(grid)
library(haven) #read_dta
library(nlme)
library(JMbayes2)
```

```{r data}
data<-read_dta("PICC dynamic prediction v4.dta")

write.csv(data,"data.csv",row.names = F)  # need to be csv file, otherwise it fails
datanew<-read.csv("data.csv")  #import data again

#Update data: PCP66 is a male, baseline age is 74.8

datanew$sex[datanew$originalid=="PCP66"]<-0  #male is 0
datanew$agebl[datanew$originalid=="PCP66"]<-74.8

#update P150 H&Y year2 is 2 not 0
#update P757 H&Y year1 is 1.5 not 0

datanew$hyyr2[datanew$originalid=="P150"]<-2
datanew$hyyr1[datanew$originalid=="P757"]<-1.5

#UPDATE P195 need to be exclude cos patient decline the follow-up and without the visit date only mmse value in medical record

datanew<-datanew%>%
  filter(originalid!="P195")

datanew[datanew$originalid=="PCP46",]

```

```{r select variables need}

#Baseline age, sex, years of education, presence of hallucinations, cognitive symptoms (none, vs yes but not impairing functioning, vs yes and impairing functioning), ? H&Y stage, MDS-UPDRS part 3, (MMSE).

data1<-datanew%>%
  select("study","idpicc","originalid","incidencecase","agebl","sex","hybl",
         "smoking",
         "mdsupdrspart3bltotalconvertedasa", "yearseducation",
         "mdsupdrsbl102hallucinations", "updrsblitem2thoughtdisorders",
         "mdsupdrsbl101cognitive","updrsblitem1intellectual",
         "mmsebltotal","mmseyr1total","mmseyr2total","mmseyr3total","mmseyr4total","mmseyr4total","mmseyr5total","mmseyr6total","mmseyr7total","mmseyr8total","mmseyr9total","mmseyr10total","mmseyr11total","mmseyr11total","mmseyr12total","datevisitbl","datevisityr1","datevisityr2","datevisityr3","datevisityr4","datevisityr5","datevisityr6","datevisityr7","datevisityr8","datevisityr9","datevisityr10","datevisityr11","datevisityr12","datevisityr13","datevisityr14","datevisityr15","datelastseen","datelastknownalive","datedeath","datedementia","datelost","losttofollowup","dead")



data1$study<-factor(data1$study,
                    levels = c(1,2,3,4,5,6),
                    labels= c("CamPalGN","ICICLE","NYPUM","ParkWest","PICNICS","PINE"))


#daily levodopa equivalent dose in ParkWest were all zero in baseline

#----change into factor---

data1$sex<-factor(data1$sex,
                    levels = c(0,1),
                    labels= c("male","female"))


#UPDATE PCP46 and PCP66 both male

data1[data1$originalid=="PCP46",]$sex<-"male"
data1[data1$originalid=="PCP46",]$idpicc<-1692
data1[data1$originalid=="PCP66",]$sex<-"male"
data1[data1$originalid=="PCP66",]$idpicc<-1693


#Chang smoking to yes/no as the imputation works better
#data1$smoking<-factor(data1$smoking,
#                    levels = c(1,2,3),
#                    labels= c("current smoker","ex smoker","never smoker"))

data1$smoking<-ifelse(data1$smoking<3,
                      1,2) #then 1 and 2 will be 1, 3 will be 2

data1$smoking<-factor(data1$smoking,
                      levels = c(1,2),
                      labels = c("yes","no"))



#------Create index for hallucinations------

data1$updrshallucinations<-ifelse(data1$mdsupdrsbl102hallucinations>0,1,0)  # 1=yes,0=no

data1$updrsthoughtdisorders<-ifelse(data1$updrsblitem2thoughtdisorders>1,1,0)  # 1=yes (2-4),0=no (0-1)

data1<-data1 %>%
      mutate(hallucinationsindex=updrshallucinations)%>%           
      mutate(hallucinationsindex=coalesce(hallucinationsindex,updrsthoughtdisorders)) #if updrshallucinations not find then use updrsthoughtdisorders

data1$hallucinationsindex<-factor(data1$hallucinationsindex,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))



#-----Create index for cognitive (3 categories)---------

#Cognitive symptoms as measured by UPDRS item 1 (intellectual impairment)/MDS-UPDRS item 1 (cognitive impairment), categorized as 0 (no cognitive symptoms), 1 (cognitive symptoms, not impairing functioning), 2+ (cognitive symptoms impairing functioning).

#data1$mdsupdrsbl101cognitive[data1$mdsupdrsbl101cognitive>1]<-2
#data1$updrsblitem1intellectual[data1$updrsblitem1intellectual>1]<-2

#data1<-data1 %>%
#      mutate(cognitiveindex=mdsupdrsbl101cognitive)%>%           
#      mutate(cognitiveindex=coalesce(cognitiveindex,updrsblitem1intellectual)) 


#0 is no cognitive symptoms, 1 is cognitive symptoms, not impairing functioning, 2 is cognitive symptoms impairing functioning

#data1$cognitiveindex<-factor(data1$cognitiveindex,
#                             levels = c(0,1,2),
#                             labels = c("no cognitive symptoms", "cognitive symptoms but not impairing functioning","cognitive symptoms impairing functioning"))

#------Create index for cognitive (yes/no)-------

#Cognitive symptoms as measured by UPDRS item 1 (intellectual impairment)/MDS-UPDRS item 1 (cognitive impairment), categorized as 0-1 (no cognitive symptoms), >1 (cognitive symptoms)

data1$mdsupdrsbl101cognitive[data1$mdsupdrsbl101cognitive>1]<-1     
data1$updrsblitem1intellectual[data1$updrsblitem1intellectual>1]<-1
data1<-data1 %>%
      mutate(cognitiveindex=mdsupdrsbl101cognitive)%>%           
      mutate(cognitiveindex=coalesce(cognitiveindex,updrsblitem1intellectual))  # 0=no,1=yes

data1$cognitiveindex<-factor(data1$cognitiveindex,
                                  levels = c(0,1),
                                  labels = c ("no","yes"))


table(data1$study,data1$hallucinationsindex)
table(data1$study,data1$cognitiveindex)

#ICICLE missing all 

#If to include those two predictors, we need to exclude ICICLE

data1%>%
  group_by(study)%>%
  count()
```


```{r cens events}

#-----create events/censoring years------

data1<-data1 %>%
  mutate(t=datedementia)%>%           
  mutate(t=coalesce(t,datelastknownalive))%>%
  mutate(t=coalesce(t,datelastseen))

#if patients have the date of dementia then t is the date of dementia. If patients without date of dementia, then the censoring date will be the date of last know alive. If patients without the date of last know alive then the censoring date will be the date last seen. Because I found some patients with date of lost is much later than the last seen, but the measurement stop in the last seen visiting year.


#sum(is.na(data2$t)) # 0 missing



data1$cens<-ifelse(is.na(data1$datedementia),0,1)  #0=right censored, 1=event 

data1$tt<-as.Date(as.character(data1$t), format="%Y-%m-%d")-
                as.Date(as.character(data1$datevisitbl), format="%Y-%m-%d")

data1$tt<-as.numeric(data1$tt)

data1$years<-data1$tt/365.25  #1222 rows

data1%>%
  filter(tt==0)%>%
  group_by(study)%>%
  count(cens)            #cens=0 CamPalGN 21 ICICLE 3 NYPUM 8 ParkWest 3 PICNICS 29 PINE 6

#need to be specify what is the reason they been removed

data1%>%
  filter(tt<0)%>%
  group_by(study)%>%
  count()          #PINE 4, already has dementia before baseline visit


data1[is.na(data1$years),] #One patients in PICNICS, originalid==PCP66, no censoring date, so have to remove


data1<-data1%>%
  filter(data1$years>0) #1080 removed 142 patients 

data1%>%
  group_by(study)%>%
  count() #882 after remove ICICLE


data1%>%
  group_by(study)%>%
  summarise(sum(cens))


data1%>%
  group_by(study)%>%
  count()
```


```{r up to 10 years}


#only 57 over 10 years

data1.temp10<-survSplit(Surv(years, cens) ~ ., data = data1, cut = 10,
                  episode="timegroup")


data1.10.all<-subset(data1.temp10, timegroup == 1) #only the first 10 year

#---No need for ICICLE----

data1.10<-data1.10.all%>%
  filter(study!="ICICLE")

data1.10%>%
  group_by(study)%>%
  count()

```


```{r impute baseline data}
#impute data first before it change to longitudinal data

data.rename.noIC<-data1.10%>%  #rember to change to data1.10.remove
  rename("Age at baseline"=agebl, 
         "Sex"=sex,
         "MDS-UPDRS part3"=mdsupdrspart3bltotalconvertedasa,"Hoehn and Yahr Scale"=hybl, "Smoking"=smoking,
         "Years of education"=yearseducation,
         "Hallucinations"=hallucinationsindex,"Cognitive symptoms"= cognitiveindex
         ) #

explanatory<-c("Smoking","Years of education","MDS-UPDRS part3","Hoehn and Yahr Scale","Hallucinations","Cognitive symptoms") 
dependent<- c("cens","tt") #"Smoking"

png("missingp.png",width = 3000,height =2000,res = 400)

mispattern<-data.rename.noIC %>% 
  missing_pattern(explanatory)

dev.off()

#---check how many missing at least one---

colnames(data1.10[,c(8,9,10,53,54)])

nrow(data1.10[complete.cases(data1.10[,c(8,9,10,53,54)]),])  #822 in data1.10

(882-822)/882 #0.07

#colnames(data1.10.remove)

#nrow(data1.10.remove[complete.cases(data1.10.remove[,c(9,10,53,54)]),]) #827 after remove smoking

(878-827)/878

```

```{r impute baseline data}

#-----EXCLUDE ICICLE----

data1.10$cons<-1

data1.10$nelsonaalen<-nelsonaalen(data1.10,years,cens) #0 is right censor,1 is event

Y<- data1.10[,c("smoking","yearseducation","mdsupdrspart3bltotalconvertedasa","hallucinationsindex","cognitiveindex")]  #


X<-data1.10[,c("cons","agebl","sex","hybl","nelsonaalen")] #adding Nelson-Aalen estimate  

clus<-data1.10$study

imp.dry<-jomo.MCMCchain(Y = Y,X = X,clus = clus, nburn = 2)

set.seed(15678)
imp1 <- jomo.MCMCchain(Y = Y, X = X, clus = clus, nburn = 5000)


#head(imp1$collectbeta) # check beta

#plot trace for each parameter value

#png("Jomo1.png",width = 3500,height =2000,res = 400)

#par(mfrow=c(2,4))

plot(imp1$collectbeta[1, 1, 1:5000], type = "l", ylab = expression(beta["education(years),0"]),
     xlab = "Iteration number" )

plot(imp1$collectbeta[1, 2, 1:5000], type = "l", ylab = expression(beta["mdsupdrspart3,0"]),
     xlab = "Iteration number" )

plot(imp1$collectbeta[1, 3, 1:5000], type = "l", ylab = expression(beta["hallucinationsindex.1 ,0"]),
     xlab = "Iteration number" )

plot(imp1$collectbeta[1, 4, 1:5000], type = "l", ylab = expression(beta["cognitiveindex.1,0"]),
     xlab = "Iteration number" ) 

plot(imp1$collectbeta[1, 5, 1:5000], type = "l", ylab = expression(beta["smoking.1,0"]),
     xlab = "Iteration number" ) 

#plot(imp1$collectbeta[1, 6, 1:5000], type = "l", ylab = expression(beta["smoking.2,0"]),
#     xlab = "Iteration number" ) 

#plot(imp1$collectbeta[1, 4, 1:5000], type = "l", ylab = expression(beta["cognitiveindex.1,0"]),
#     xlab = "Iteration number" ) 

#plot(imp1$collectbeta[1, 5, 1:5000], type = "l", ylab = expression(beta["cognitiveindex.2,0"]),
#     xlab = "Iteration number" ) 



#plot trace for cov matrix element
#imp1$collectomega[,,1] #check the row and col name
#Category variable don't need to plot, just a straight line

plot(imp1$collectomega[1, 1, 1:5000], type = "l", ylab = expression(omega[education(years),1,1]^2),
     xlab = "Iteration number" )
plot(imp1$collectomega[2, 2, 1:5000], type = "l", ylab = expression(omega[MDS-UPDRS,1,1]^2),
     xlab = "Iteration number" )


#dev.off()


# Capture the state of the sampler as starting values for the second set of iterations:
beta.start <- imp1$collectbeta[,,5000] # capture the fixed parameter values
l1cov.start <- imp1$collectomega[,,5000] # capture the level-1 covariance matrix values
start.imp <- imp1$finimp.latnorm # capture the final imputed data set 



#Re-run the same function for a larger number of iterations
imp2 <- jomo.MCMCchain(Y = Y, X = X, clus = clus, beta.start = beta.start, l1cov.start = l1cov.start,
                       start.imp = start.imp, nburn = 5000)

# Check the trace again

#png("Jomo2.png",width = 3500,height =2000,res = 400)

#par(mfrow=c(2,4))

plot(imp2$collectbeta[1, 1, 1:5000], type = "l", ylab = expression(beta["education(years),0"]),
     xlab = "Iteration number" )

plot(imp2$collectbeta[1, 2, 1:5000], type = "l", ylab = expression(beta["mdsupdrspart3,0"]),
     xlab = "Iteration number" )

plot(imp2$collectbeta[1, 3, 1:5000], type = "l", ylab = expression(beta["hallucinationsindex.1,0"]),
     xlab = "Iteration number" ) 

plot(imp2$collectbeta[1, 4, 1:5000], type = "l", ylab = expression(beta["cognitiveindex.1,0"]),
     xlab = "Iteration number" ) 

plot(imp2$collectbeta[1, 5, 1:5000], type = "l", ylab = expression(beta["smoking.1,0"]),
     xlab = "Iteration number" ) 

#plot(imp2$collectbeta[1, 6, 1:5000], type = "l", ylab = expression(beta["smoking.2,0"]),
#     xlab = "Iteration number" ) 

#plot trace for cov matrix element

plot(imp2$collectomega[1, 1, 1:5000], type = "l", ylab = expression(omega[education(years),1,1]^2),
     xlab = "Iteration number" )

plot(imp2$collectomega[2, 2, 1:5000], type = "l", ylab = expression(omega[mdsupdrspart3,1,1]^2),
     xlab = "Iteration number" )

#dev.off()

#collect posterior mean of cov matrix
l1cov.guess <- apply(imp2$collectomega, c(1, 2), mean)

dim(imp2$collectomega[,,1]) #degrees of freedom is 6

# Multiply by degrees of freedom to get scale matrix

l1cov.prior <- l1cov.guess*5

# Perform multilevel imputation:
imp3 <- jomo(Y = Y, X = X, clus = clus, l1cov.prior = l1cov.prior, nburn = 5000, nbetween = 1000, nimp = 9,meth = "random" )  #The nimp is the precentage of missing 


```

```{r merge data baseline}

names(imp3)
dim(imp3)
#View original (partially observed) data:
head(imp3)
# View last imputation (the left most column is the row number):
head(imp3[imp3$Imputation == 1,])

#create id to merge the data 

data1.10$id<-seq(nrow(data1.10)) 

data1.10.mmse<-data1.10%>%
  select("id","study","idpicc","originalid",
         "mmsebltotal","mmseyr1total","mmseyr2total","mmseyr3total","mmseyr4total","mmseyr4total","mmseyr5total","mmseyr6total","mmseyr7total","mmseyr8total","mmseyr9total","mmseyr10total","mmseyr11total","mmseyr11total","mmseyr12total","datevisitbl","datevisityr1","datevisityr2","datevisityr3","datevisityr4","datevisityr5","datevisityr6","datevisityr7","datevisityr8","datevisityr9","datevisityr10","datevisityr11","datevisityr12","datevisityr13","datevisityr14","datevisityr15","cens","tt","years")

imp3.new<-merge(imp3,data1.10.mmse,by.x = "id",by.y = "id")

colnames(imp3.new)
```


```{r check the imputation set}

#summary(imp3.new) #All summary value looks good, no negative

imp3.new$age10<-imp3.new$agebl/10

imp3.new$mdsupdrs3.10<-imp3.new$mdsupdrspart3bltotalconvertedasa/10

summary(imp3.new$mdsupdrspart3bltotalconvertedasa)

data.imp<-imputationList(split(imp3.new, imp3.new$Imputation)[-1])

imp3.new%>%
  filter(Imputation==2)%>%
  filter(study=="PINE")%>%
  count(hallucinationsindex)


imp3.new%>%
  filter(Imputation==5)%>%
  filter(study=="PINE")%>%
  count(hallucinationsindex)

```

```{r extract 9 imputed dataset}
 
#There will be need to create 8 different imputation in baseline and longitudinal

data.imp.new_names <- paste("data.imp",1:9,sep="")  # create names first

imp.list<-data.imp[["imputations"]]

# Loop through the indices of the list
for (i in 1:9) {
  # Extract the dataset based on the index
  extracted_dataset <- imp.list[[i]]
  
  # Assign the extracted dataset to the corresponding variable
  assign(paste0("data.imp", i), extracted_dataset)
}

```


```{r change long format (longitudinal) for data.imp1-9}

#-----create follow-up times in years----

# List of dataset names
dataset_names <- c("data.imp1","data.imp2", "data.imp3", "data.imp4", "data.imp5", "data.imp6", "data.imp7", "data.imp8","data.imp9")

# Loop through each dataset
for (name in dataset_names) {
  # Get the dataset
  dataset <- get(name)
  
  # Convert columns with "datevisityr" prefix to Date format
  year_names <- paste0("datevisityr", 1:15)
  dataset[, year_names] <- lapply(dataset[, year_names], as.Date, format = "%Y-%m-%d")
  
  # Convert 'datevisitbl' column to Date format
  dataset$datevisitbl <- as.Date(dataset$datevisitbl, format = "%Y-%m-%d")
  
  # Calculate year differences and create new variables
  year_names2 <- paste0("year", 1:15)
  for (i in 1:15) {
    year <- as.numeric(dataset[[paste0("datevisityr", i)]] - dataset$datevisitbl) / 365.25
    dataset[[year_names2[i]]] <- year
  }
  # Update the dataset in the environment
  assign(name, dataset)
}

for (name in dataset_names) {
  # Get the dataset
  dataset <- get(name)
  # Select specific columns
  dataset <- dataset[, c(1:31, 47:66)]
  
  # Update the dataset in the environment
  assign(name, dataset)
}

#add one columns year0 and 0 to all 9 imputation dataset

data.imp1$year0<-0
data.imp2$year0<-0
data.imp3$year0<-0
data.imp4$year0<-0
data.imp5$year0<-0
data.imp6$year0<-0
data.imp7$year0<-0
data.imp8$year0<-0
data.imp9$year0<-0



#----create year follow-up----

# Loop through each dataset
for (i in seq_along(dataset_names)) {
  # Get the dataset
  dataset <- get(dataset_names[i])
  
  # Perform pivot_longer operation
  long_dataset <- dataset %>%
    pivot_longer(
      cols = c(`year0`, `year1`:`year15`),
      names_to = "visityear",
      values_to = "followupyears",
      values_transform = ~ as.numeric(gsub(",", "", .x)),
      values_drop_na = TRUE
    )
  
  # Assign the result to the years_long dataset
  assign(paste0("years_long.", i), long_dataset)
}



#change mmseyr to year1 to year12 
#add mmsebl to year0

for (i in seq_along(dataset_names)) {
  # Get the dataset
  dataset <- get(dataset_names[i])
  
  # Select specific columns
  MMSE_data <- dataset %>%
    select("id", "clus", "idpicc", "originalid", "study", "mmsebltotal",
           "mmseyr1total", "mmseyr2total", "mmseyr3total", "mmseyr4total",
           "mmseyr5total", "mmseyr6total", "mmseyr7total", "mmseyr8total",
           "mmseyr9total", "mmseyr10total", "mmseyr11total", "mmseyr12total")
  
  # Rename selected columns
  colnames(MMSE_data)[6:18] <- c("year0","year1", "year2", "year3", "year4",
                                 "year5", "year6", "year7", "year8",
                                 "year9", "year10", "year11", "year12")
  
  # Perform pivot_longer operation
  mmse_long <- MMSE_data %>%
    pivot_longer(
      cols = `year0`:`year12`,
      names_to = "visityear",
      values_to = "mmse",
      values_transform = ~ as.numeric(gsub(",", "", .x)),
      values_drop_na = TRUE
    )
  
  # Assign the result to the mmse_long dataset
  assign(paste0("mmse_long.", i), mmse_long)
}

```

```{r cmobine long format dataset 1}
#-----combine all long tidy------

nrow(years_long.1)  #5317
nrow(mmse_long.1)   #4618


years_long.new.1<-years_long.1%>%
  select("id","study","idpicc","originalid",
         "agebl","sex","hybl","Imputation",
         "smoking","yearseducation",
         "mdsupdrspart3bltotalconvertedasa",
         "hallucinationsindex",
         "cognitiveindex",
         "cens","years","followupyears","visityear")


mmse_long.new.1<-mmse_long.1%>%
  select("id","study","idpicc","visityear","mmse")

data_long.1<-merge(years_long.new.1, mmse_long.new.1, by = c("id","study","idpicc","visityear"),all.x = T,all.y = T)

data_long.1<-data_long.1[order(data_long.1$id,data_long.1$visityear), ]




# List of dataset indices
dataset_indices <- 1:9

for (i in dataset_indices) {
  # Get the years_long dataset
  years_long_data <- get(paste0("years_long.", i))
  
  # Select specific columns
  years_long_selected <- years_long_data %>%
    select("id", "study", "idpicc", "originalid", "agebl", "sex", "hybl",
           "yearseducation","Imputation",
           "smoking", "mdsupdrspart3bltotalconvertedasa", "hallucinationsindex",
           "cognitiveindex", "cens", "years", "followupyears", "visityear")
  
  # Get the mmse_long dataset
  mmse_long_data <- get(paste0("mmse_long.", i))
  
  # Select specific columns
  mmse_long_selected <- mmse_long_data %>%
    select("id", "study", "idpicc", "visityear", "mmse")
  
  # Merge years_long and mmse_long datasets
  data_long <- merge(years_long_selected, mmse_long_selected,
                     by = c("id", "study", "idpicc", "visityear"),
                     all.x = TRUE, all.y = TRUE)
  
  # Order the merged dataset
  data_long <- data_long[order(data_long$id, data_long$visityear), ]
  
  # Assign the result to the data_long dataset
  assign(paste0("data_long.", i), data_long)
}

```


```{r check missing age in longtitude datasets}

#----check age----

data_long.1%>%
  group_by(study)%>%
  count(is.na(agebl))
#2 patints in PINE missing agebl

data_long.1%>%
  filter(study=="PINE")%>%
  filter(is.na(agebl))
#idpicc 1170 1235 1261 

#1170 The follow-up time is end in 10 years,patient has mmse value on 11 and 12 years. 
#1261 The follow-up time is end in 9 years, patient has mmse value on 10 and 11 years.

#------remove value outside the last seen date-----

#Due to the data just medical records not real follow-up we remove it

#data_long.1<-data_long.1[!is.na(data_long.1$agebl),]

for (i in 1:9) {
  # Get the data_long dataset
  data_long <- get(paste0("data_long.", i))
  
  # Remove rows with NA values in agebl column
  data_long_cleaned <- data_long[!is.na(data_long$agebl), ]
  
  # Assign the cleaned dataset back to the environment
  assign(paste0("data_long.", i), data_long_cleaned)
}

#----check sex----

data_long.5%>%
  group_by(study)%>%
  count(is.na(sex))

```


```{r create longitudinal data1}

#data_long.1[complete.cases(data_long.1),]

data_long.1<-data_long.1[!is.na(data_long.1$mmse),]


for (i in 1:9) {
  # Get the data_long dataset
  data_long <- get(paste0("data_long.", i))
  
  # Remove rows with NA values in agebl column
  data_long_cleaned <- data_long[!is.na(data_long$mmse), ]
  
  # Assign the cleaned dataset back to the environment
  assign(paste0("data_long.", i), data_long_cleaned)
}

#unique(data_long.1$id) 896 same as nrow(data.baseline)

#data_long.1<-data_long.1[data_long.1$years!=data_long.1$followupyears,]


for (i in 1:9) {
  # Get the data_long dataset
  data_long <- get(paste0("data_long.", i))
  
  # Remove rows with NA values in agebl column
  data_long_cleaned <- data_long[!is.na(data_long$agebl), ]
  
  # Assign the cleaned dataset back to the environment
  assign(paste0("data_long.", i), data_long_cleaned)
}


for (i in 1:9) {
  # Get the data_long dataset
  data_long <- get(paste0("data_long.", i))
  
  # Remove rows where years is not equal to followupyears
  data_long_cleaned <- data_long[data_long$years != data_long$followupyears, ]
  
  # Assign the cleaned dataset back to the environment
  assign(paste0("data_long.", i), data_long_cleaned)
}

```


```{r create baseline data1}

data.baseline.1<-data.imp1%>%
  select("id","study","idpicc","originalid","agebl","sex","hybl","mdsupdrspart3bltotalconvertedasa","yearseducation","smoking","hallucinationsindex","cognitiveindex","cens","tt","years","Imputation")

data.baseline.1$age10<-data.baseline.1$agebl/10

data.baseline.1$mdsupdrs3.10<-data.baseline.1$mdsupdrspart3bltotalconvertedasa/10


# Loop through each dataset
for (i in seq_along(dataset_names)) {
  # Get the dataset
  dataset <- get(dataset_names[i])
  
  # Select specific columns
  data_baseline <- dataset %>%
    select("id", "study", "idpicc", "originalid", "agebl", "sex", "hybl", "mdsupdrspart3bltotalconvertedasa", "yearseducation","smoking", "hallucinationsindex", "cognitiveindex", "cens", "tt", "years","Imputation")
  
  # Create new columns
  data_baseline$age10 <- data_baseline$agebl / 10
  data_baseline$mdsupdrs3.10 <- data_baseline$mdsupdrspart3bltotalconvertedasa / 10
  
  # Assign the result to the data_baseline dataset
  assign(paste0("data.baseline.", i), data_baseline)
}
```

```{r remove unused levels}

levels(data.baseline.2$study)

data.baseline.1$study<-droplevels(data.baseline.1$study)
data.baseline.2$study<-droplevels(data.baseline.2$study)
data.baseline.3$study<-droplevels(data.baseline.3$study)
data.baseline.4$study<-droplevels(data.baseline.4$study)
data.baseline.5$study<-droplevels(data.baseline.5$study)
data.baseline.6$study<-droplevels(data.baseline.6$study)
data.baseline.7$study<-droplevels(data.baseline.7$study)
data.baseline.8$study<-droplevels(data.baseline.8$study)
data.baseline.9$study<-droplevels(data.baseline.9$study)


data_long.2$study<-droplevels(data_long.2$study)

levels(data_long.2$study)

#Check if they match

diff_id<-setdiff(unique(data.baseline.2$id),unique(data_long.2$id))

diff_idpicc<-setdiff(unique(data.baseline.2$idpicc),unique(data_long.2$idpicc))

#148 151 174 251 
#idpicc
#328 331 354 436 

data1%>%
  filter(idpicc %in% diff_idpicc)%>%
  group_by(study)%>%
  count()

#These 5 patients have no record in MMSE at baseline and followup, all MMSE value are missing
# 4 in NYPUM and 1 in PINE

#----remove patients without any MMSE records in baseline dataset---

data.baseline.2<-data.baseline.2%>%
  filter(!idpicc %in% diff_idpicc)


data.baseline.2%>%
  group_by(study)%>%
  count()

```


```{r Characteristic baseline}

data1.10.remove<-data1.10%>%
  filter(! idpicc %in% diff_idpicc)


data1.10.remove%>%
  group_by(study)%>%
  summarise(round(mean(agebl),1),round(sd(agebl),1))

data1.10.remove%>%
  summarise(round(mean(agebl),1),round(sd(agebl),1))

#data1.10.remove$sex<-factor(data1.10.remove$sex,
#                    levels = c(1,2),
#                    labels= c("male","female"))

table(data1.10.remove$sex,data1.10.remove$study)


data1.10.remove%>%
  group_by(study)%>%
  summarise(round(median(hybl),1),round(quantile(hybl),1))

data1.10.remove%>%
  summarise(round(median(hybl),1),round(quantile(hybl),1))


data1.10.remove%>%
  group_by(study)%>%
  summarise(round(median(mdsupdrspart3bltotalconvertedasa,na.rm=T),1),round(quantile(mdsupdrspart3bltotalconvertedasa,na.rm=T),1))

data1.10.remove%>%
  summarise(round(median(mdsupdrspart3bltotalconvertedasa,na.rm=T),1),round(quantile(mdsupdrspart3bltotalconvertedasa,na.rm=T),1))


data1.10.remove%>%
  filter(is.na(mdsupdrspart3bltotalconvertedasa))%>%
  group_by(study)%>%
  count()


data1.10.remove%>%
  group_by(study)%>%
  summarise(round(mean(yearseducation,na.rm=T),1),round(sd(yearseducation,na.rm=T),1))

data1.10.remove%>%
  summarise(round(mean(yearseducation,na.rm=T),1),round(sd(yearseducation,na.rm=T),1))

data1.10.remove%>%
  filter(is.na(yearseducation))%>%
  group_by(study)%>%
  count()


table(data1.10.remove$hallucinationsindex,data1.10.remove$study)
  

data1.10.remove%>%
  filter(is.na(hallucinationsindex))%>%
  group_by(study)%>%
  count()

table(data1.10.remove$study,data1.10.remove$cognitiveindex)

table(data1.10.remove$cognitiveindex)

data1.10.remove%>%
  filter(is.na(cognitiveindex))%>%
  group_by(study)%>%
  count()


data1.10.remove%>%
  group_by(study)%>%
  summarise(round(median(mmsebltotal,na.rm=T),1),round(quantile(mmsebltotal,na.rm=T),1))

data1.10.remove%>%
  summarise(round(median(mmsebltotal,na.rm=T),1),round(quantile(mmsebltotal,na.rm=T),1))


data1.10.remove%>%
  filter(is.na(mmsebltotal))%>%
  group_by(study)%>%
  count()


data1.10.remove%>%
  filter(is.na(smoking))%>%
  group_by(study)%>%
  count()

table(data1.10.remove$smoking,data1.10.remove$study)


#event
data1.10.remove%>%
  #group_by(study)%>%
  summarise(sum(cens)) # 0 is censoring

data1.10.remove%>%
  group_by(study)

data1.10%>%
  filter(losttofollowup==1)%>%
  group_by(study)%>%
  count() 


#without the date of death
#data1.10.remove%>%
#  group_by(study)%>%
#  filter(dead==1)%>%  #But know death
#  count()

data1.10.remove%>%
  group_by(study)%>%
  filter(cens!=1)%>%
  filter(!is.na(datedementia))%>%
  count()#Those patients got dementia later than 10 years, but I cut the time 10 years. 6 in PINE, 1 in NYPUM

```


```{r KM plot}

KM<-survfit(Surv(years,cens)~study,data=data1.10.remove)


ggsurv1<-ggsurvplot(KM,
           ylab="Cumulative probability of dementia",
           xlab="Time to dementia",
           legend="top",
           surv.median.line = "hv",
           fun="event",
           risk.table = T,
           risk.table.y.text.col = F,
           risk.table.y.text = T,
           risk.table.col = "strata",
           linetype = "strata",
           ggtheme = theme_bw(),
           legend.labs=c("CamPalGN","NYPUM","ParkWest","PICNICS","PINE"))

ggsurv1<-ggpar(ggsurv1, 
      font.main = c(14, "bold"),
      font.x = c(14, "bold"),
      font.y = c(14, "bold"),
      font.caption = c(14, "bold"), 
      font.legend = c(14, "bold"))

print(ggsurv1, 
      surv.plot.height = 0.6,
      risk.table.height = 0.4)


png("KM1.dementia.png",width = 4000,height =3000,res = 400)

print(ggsurv1, 
      surv.plot.height = 0.7,
      risk.table.height = 0.3)

dev.off()


```


```{r Reverse Kaplan-Meier estimate of the median follow-up time}

data1.10.remove$cens.followup<-1-data1.10.remove$cens
reverse.KM<-survfit(Surv(years,cens.followup)~study,data=data1.10.remove)

#survfit(Surv(years,cens.followup)~1,data=data1.10.remove)

```



```{r event/incidence}

data1.10.remove%>%
  group_by(study)%>%
  summarise('Incidence rate'=paste(round(sum(cens)/as.numeric(sum(years))*100,1),' per 100 person-years'))

```


