---
title: "Dementia MM IECV"
output: html_document
date: "2024-01-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r IECV outline PICNICS}

#Leave the PICNICS study out as external validation

#So the development model will be based on CamPalGN PINE NYPUM ParKwest

#And the validation dataset will be PICNICS. Therefore, we need to decide which study looks most simliar to PICNICS and use this study fixed effect to refit the PICNICS study. From the KM curves, I think PINE has the most similar patter in the first 4 year. And looking at the baseline characteristics,it also is PINE. Although incidence rate is closer to Parkwest, I think that is because high censoring later. 

#Hence I chose PINE 

```

```{r IECV PICNICS}

#---development dataset---

IECV_devlong_1<-data_long.fit.up%>%
  filter(study!="PICNICS")

IECV_devbase_1<-data.baseline.fit.up%>%
  filter(study!="PICNICS")

IECV_devlong_1$study<-droplevels(IECV_devlong_1$study)
IECV_devbase_1$study<-droplevels(IECV_devbase_1$study)


#----validation dataset---

IECV_vlong_1<-data_long.fit.up%>%
  filter(study=="PICNICS")

IECV_vlong_1$study<-droplevels(IECV_vlong_1$study)

#----development model----

mmse.dev1<-lme(mmse~study+agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_devlong_1)

mds.dev1<-lme(MDSUPDRS3~study+agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_devlong_1)

Mixed_dev1<-list(mmse.dev1,mds.dev1) 

Cox_dev1<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl+study,data=IECV_devbase_1, x = TRUE,model = TRUE) 

#jm_dev1<-jm(Cox_dev1,Mixed_objects = Mixed_dev1,time_var = "followupyears") 

summary(jm_dev1)

#----validate in the PICNICS---

#Change the study to ParkWest

levels(IECV_devlong_1$study)

levels(IECV_vlong_1$study)<-c("ParkWest","CamPalGN","PICNICS","PINE") #Only take PINE levels, other levels won't be used

roc.PIC.0<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 0,Dt=3,cores=1L)
roc.PIC.1<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 1,Dt=3,cores=1L)
roc.PIC.2<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 2,Dt=3,cores=1L)
roc.PIC.3<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 3,Dt=3,cores=1L)
roc.PIC.4<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 4,Dt=3,cores=1L)
roc.PIC.5<-tvROC(jm_dev1,newdata=IECV_vlong_1,Tstart = 5,Dt=3,cores=1L)


tvAUC(roc.PIC.0)
tvAUC(roc.PIC.1)
tvAUC(roc.PIC.2)
tvAUC(roc.PIC.3)
tvAUC(roc.PIC.4)
tvAUC(roc.PIC.5)


#png("IECV-PIC.png",width = 3500,height =2000,res = 400)
#par(mfrow=c(2,3))
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 3,Dt=3,plot = TRUE)
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 4,Dt=3,plot = TRUE)
calibration_plot(jm_dev1,newdata = IECV_vlong_1,Tstart = 5,Dt=3,plot = TRUE)
#dev.off()

```

```{r IECV NYPUM (model without PICNICS)}

#----development dataset----

IECV_devlong_NY<-data_long.fit.up.noPIC%>%
  filter(study!="NYPUM")

IECV_devbase_NY<-data.baseline.fit.up.noPIC%>%
  filter(study!="NYPUM")

IECV_devlong_NY$study<-droplevels(IECV_devlong_NY$study)
IECV_devbase_NY$study<-droplevels(IECV_devbase_NY$study)

IECV_devbase_NY$study<-factor(IECV_devbase_NY$study,levels=c("PINE","CamPalGN","ParkWest")) #put PINE as the first level
IECV_devlong_NY$study<-factor(IECV_devlong_NY$study,levels=c("PINE","CamPalGN","ParkWest")) 

#----validation dataset----

IECV_vlong_NY<-data_long.fit.up.noPIC%>%
  filter(study=="NYPUM")

IECV_vlong_NY$study<-droplevels(IECV_vlong_NY$study)

#----development model----

mmse.dev.NY<-lme(mmse~study+agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_devlong_NY)

mds.dev.NY<-lme(MDSUPDRS3~study+agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_devlong_NY)

Mixed_dev.NY<-list(mmse.dev.NY,mds.dev.NY) 

Cox_dev.NY<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl+study,data=IECV_devbase_NY, x = TRUE,model = TRUE)  

#jm_dev.NY<-jm(Cox_dev.NY,Mixed_objects = Mixed_dev.NY,time_var = "followupyears") 

summary(jm_dev.NY)

#----validate in the NYPUM----

#Change the study to CamPalGN 

levels(IECV_devlong_NY$study)

levels(IECV_vlong_NY$study)<-c("CamPalGN","PINE","ParkWest") #Only take CamPalGN levels, other levels won't be used

roc.NY.0<-tvROC(jm_dev.NY,newdata=IECV_vlong_NY,Tstart = 0,Dt=3,cores=1L)
roc.NY.1<-tvROC(jm_dev.NY,newdata=IECV_vlong_NY,Tstart = 1,Dt=3,cores=1L)
roc.NY.2<-tvROC(jm_dev.NY,newdata=IECV_vlong_NY,Tstart = 2,Dt=3,cores=1L)
roc.NY.3<-tvROC(jm_dev.NY,newdata=IECV_vlong_NY,Tstart = 3,Dt=3,cores=1L)
roc.NY.4<-tvROC(jm_dev.NY,newdata=IECV_vlong_NY,Tstart = 4,Dt=3,cores=1L)
roc.NY.5<-tvROC(jm_dev.NY,newdata=IECV_vlong_NY,Tstart = 5,Dt=3,cores=1L)
roc.NY.6<-tvROC(jm_dev.NY,newdata=IECV_vlong_NY,Tstart = 6,Dt=3,cores=1L)



tvAUC(roc.NY.0)
tvAUC(roc.NY.1)
tvAUC(roc.NY.2)
tvAUC(roc.NY.3)
tvAUC(roc.NY.4)
tvAUC(roc.NY.5)
tvAUC(roc.NY.6)


#png("IECV-NYPUM.png",width = 4200,height =2000,res = 400)
#par(mfrow=c(2,4))
calibration_plot(jm_dev.NY,newdata = IECV_vlong_NY,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_dev.NY,newdata = IECV_vlong_NY,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_dev.NY,newdata = IECV_vlong_NY,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_dev.NY,newdata = IECV_vlong_NY,Tstart = 3,Dt=3,plot = TRUE)
calibration_plot(jm_dev.NY,newdata = IECV_vlong_NY,Tstart = 4,Dt=3,plot = TRUE)
calibration_plot(jm_dev.NY,newdata = IECV_vlong_NY,Tstart = 5,Dt=3,plot = TRUE)
calibration_plot(jm_dev.NY,newdata = IECV_vlong_NY,Tstart = 6,Dt=3,plot = TRUE)
#dev.off()

```


```{r IECV CamPalGN (model without PICNICS)}

#----development dataset----

IECV_devlong_Cam<-data_long.fit.up.noPIC%>%
  filter(study!="CamPalGN")

IECV_devbase_Cam<-data.baseline.fit.up.noPIC%>%
  filter(study!="CamPalGN")

IECV_devlong_Cam$study<-droplevels(IECV_devlong_Cam$study)
IECV_devbase_Cam$study<-droplevels(IECV_devbase_Cam$study)

IECV_devbase_Cam$study<-factor(IECV_devbase_Cam$study,levels=c("PINE","NYPUM","ParkWest")) #put PINE as the first level
IECV_devlong_Cam$study<-factor(IECV_devlong_Cam$study,levels=c("PINE","NYPUM","ParkWest")) 

#----validation dataset----

IECV_vlong_Cam<-data_long.fit.up.noPIC%>%
  filter(study=="CamPalGN")

IECV_vlong_Cam$study<-droplevels(IECV_vlong_Cam$study)


#----development model----

mmse.dev.Cam<-lme(mmse~study+agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_devlong_Cam)

mds.dev.Cam<-lme(MDSUPDRS3~study+agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_devlong_Cam)

Mixed_dev.Cam<-list(mmse.dev.Cam,mds.dev.Cam) 

Cox_dev.Cam<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl+study,data=IECV_devbase_Cam, x = TRUE,model = TRUE)  

#jm_dev.Cam<-jm(Cox_dev.Cam,Mixed_objects = Mixed_dev.Cam,time_var = "followupyears") 

summary(jm_dev.Cam)

#----validate in the CamPalGN----

#Change the study to NYPUM 

levels(IECV_devlong_Cam$study)

levels(IECV_vlong_Cam$study)<-c("NYPUM","PINE","ParkWest") #Only take NYPUM levels, other levels won't be used

roc.Cam.0<-tvROC(jm_dev.Cam,newdata=IECV_vlong_Cam,Tstart = 0,Dt=3,cores=1L)
roc.Cam.1<-tvROC(jm_dev.Cam,newdata=IECV_vlong_Cam,Tstart = 1,Dt=3,cores=1L)
roc.Cam.2<-tvROC(jm_dev.Cam,newdata=IECV_vlong_Cam,Tstart = 2,Dt=3,cores=1L)
roc.Cam.3<-tvROC(jm_dev.Cam,newdata=IECV_vlong_Cam,Tstart = 3,Dt=3,cores=1L)
roc.Cam.4<-tvROC(jm_dev.Cam,newdata=IECV_vlong_Cam,Tstart = 4,Dt=3,cores=1L)
roc.Cam.5<-tvROC(jm_dev.Cam,newdata=IECV_vlong_Cam,Tstart = 5,Dt=3,cores=1L)
roc.Cam.6<-tvROC(jm_dev.Cam,newdata=IECV_vlong_Cam,Tstart = 6,Dt=3,cores=1L)


tvAUC(roc.Cam.0)
tvAUC(roc.Cam.1)
tvAUC(roc.Cam.2)
tvAUC(roc.Cam.3)
tvAUC(roc.Cam.4)
tvAUC(roc.Cam.5)
tvAUC(roc.Cam.6)



#png("IECV-Cam.png",width = 4200,height =2000,res = 400)
#par(mfrow=c(2,4))
calibration_plot(jm_dev.Cam,newdata = IECV_vlong_Cam,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_dev.Cam,newdata = IECV_vlong_Cam,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_dev.Cam,newdata = IECV_vlong_Cam,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_dev.Cam,newdata = IECV_vlong_Cam,Tstart = 3,Dt=3,plot = TRUE)
calibration_plot(jm_dev.Cam,newdata = IECV_vlong_Cam,Tstart = 4,Dt=3,plot = TRUE)
calibration_plot(jm_dev.Cam,newdata = IECV_vlong_Cam,Tstart = 5,Dt=3,plot = TRUE)
calibration_plot(jm_dev.Cam,newdata = IECV_vlong_Cam,Tstart = 6,Dt=3,plot = TRUE)
#dev.off()


```


```{r IECV ParkWest (model without PICNICS)}

#----development dataset----

IECV_devlong_PA<-data_long.fit.up.noPIC%>%
  filter(study!="ParkWest")

IECV_devbase_PA<-data.baseline.fit.up.noPIC%>%
  filter(study!="ParkWest")

IECV_devlong_PA$study<-droplevels(IECV_devlong_PA$study)
IECV_devbase_PA$study<-droplevels(IECV_devbase_PA$study)

IECV_devbase_PA$study<-factor(IECV_devbase_PA$study,levels=c("PINE","CamPalGN","NYPUM")) #put PINE as the first level
IECV_devlong_PA$study<-factor(IECV_devlong_PA$study,levels=c("PINE","CamPalGN","NYPUM")) 

#----validation dataset----

IECV_vlong_PA<-data_long.fit.up.noPIC%>%
  filter(study=="ParkWest")

IECV_vlong_PA$study<-droplevels(IECV_vlong_PA$study)


#----development model----

mmse.dev.PA<-lme(mmse~study+agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_devlong_PA)

mds.dev.PA<-lme(MDSUPDRS3~study+agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_devlong_PA)

Mixed_dev.PA<-list(mmse.dev.PA,mds.dev.PA) 

Cox_dev.PA<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl+study,data=IECV_devbase_PA, x = TRUE,model = TRUE)  

#jm_dev.PA<-jm(Cox_dev.PA,Mixed_objects = Mixed_dev.PA,time_var = "followupyears") 

summary(jm_dev.PA)

#----validate in the ParkWest----

#Change the study to PINE 

levels(IECV_devlong_PA$study)

levels(IECV_vlong_PA$study)<-c("PINE","NYPUM","CamPalGN") #Only take PINE levels, other levels won't be used

roc.PA.0<-tvROC(jm_dev.PA,newdata=IECV_vlong_PA,Tstart = 0,Dt=3,cores=1L)
roc.PA.1<-tvROC(jm_dev.PA,newdata=IECV_vlong_PA,Tstart = 1,Dt=3,cores=1L)
roc.PA.2<-tvROC(jm_dev.PA,newdata=IECV_vlong_PA,Tstart = 2,Dt=3,cores=1L)
roc.PA.3<-tvROC(jm_dev.PA,newdata=IECV_vlong_PA,Tstart = 3,Dt=3,cores=1L)
roc.PA.4<-tvROC(jm_dev.PA,newdata=IECV_vlong_PA,Tstart = 4,Dt=3,cores=1L)


roc.PA.0<-tvROC(jm_dev.PA,newdata=IECV_vlong_PA,Tstart = 0,Dt=7,cores=1L)
roc.PA.1<-tvROC(jm_dev.PA,newdata=IECV_vlong_PA,Tstart = 1,Dt=6,cores=1L)
roc.PA.2<-tvROC(jm_dev.PA,newdata=IECV_vlong_PA,Tstart = 2,Dt=5,cores=1L)
roc.PA.3<-tvROC(jm_dev.PA,newdata=IECV_vlong_PA,Tstart = 3,Dt=4,cores=1L)
roc.PA.4<-tvROC(jm_dev.PA,newdata=IECV_vlong_PA,Tstart = 4,Dt=3,cores=1L)


tvAUC(roc.PA.0)
tvAUC(roc.PA.1)
tvAUC(roc.PA.2)
tvAUC(roc.PA.3)
tvAUC(roc.PA.4)


png("IECV-PA.png",width = 3000,height =2000,res = 400)
par(mfrow=c(2,3))
calibration_plot(jm_dev.PA,newdata = IECV_vlong_PA,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PA,newdata = IECV_vlong_PA,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PA,newdata = IECV_vlong_PA,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PA,newdata = IECV_vlong_PA,Tstart = 3,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PA,newdata = IECV_vlong_PA,Tstart = 4,Dt=3,plot = TRUE)
dev.off()

```


```{r IECV PINE (model without PICNICS)}

#----development dataset----

IECV_devlong_PIN<-data_long.fit.up.noPIC%>%
  filter(study!="PINE")

IECV_devbase_PIN<-data.baseline.fit.up.noPIC%>%
  filter(study!="PINE")

IECV_devlong_PIN$study<-droplevels(IECV_devlong_PIN$study)
IECV_devbase_PIN$study<-droplevels(IECV_devbase_PIN$study)

IECV_devbase_PIN$study<-factor(IECV_devbase_PIN$study,levels=c("NYPUM","CamPalGN","ParkWest")) #put NYPUM as the first level
IECV_devlong_PIN$study<-factor(IECV_devlong_PIN$study,levels=c("NYPUM","CamPalGN","ParkWest")) 

#----validation dataset----

IECV_vlong_PIN<-data_long.fit.up.noPIC%>%
  filter(study=="PINE")

IECV_vlong_PIN$study<-droplevels(IECV_vlong_PIN$study)

#----development model----

mmse.dev.PIN<-lme(mmse~study+agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_devlong_PIN)

mds.dev.PIN<-lme(MDSUPDRS3~study+agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_devlong_PIN)

Mixed_dev.PIN<-list(mmse.dev.PIN,mds.dev.PIN) 

Cox_dev.PIN<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl+study,data=IECV_devbase_PIN, x = TRUE,model = TRUE)  

#jm_dev.PIN<-jm(Cox_dev.PIN,Mixed_objects = Mixed_dev.PIN,time_var = "followupyears") 

summary(jm_dev.PIN)

#----validate in the PINE----

#Change the study to PINE 

levels(IECV_devlong_PIN$study)

levels(IECV_vlong_PIN$study)<-c("NYPUM","CamPalGN","ParkWest") #Only take NYPUM levels, other levels won't be used

roc.PIN.0<-tvROC(jm_dev.PIN,newdata=IECV_vlong_PIN,Tstart = 0,Dt=3,cores=1L)
roc.PIN.1<-tvROC(jm_dev.PIN,newdata=IECV_vlong_PIN,Tstart = 1,Dt=3,cores=1L)
roc.PIN.2<-tvROC(jm_dev.PIN,newdata=IECV_vlong_PIN,Tstart = 2,Dt=3,cores=1L)
roc.PIN.3<-tvROC(jm_dev.PIN,newdata=IECV_vlong_PIN,Tstart = 3,Dt=3,cores=1L)
roc.PIN.4<-tvROC(jm_dev.PIN,newdata=IECV_vlong_PIN,Tstart = 4,Dt=3,cores=1L)
roc.PIN.5<-tvROC(jm_dev.PIN,newdata=IECV_vlong_PIN,Tstart = 5,Dt=3,cores=1L)
roc.PIN.6<-tvROC(jm_dev.PIN,newdata=IECV_vlong_PIN,Tstart = 6,Dt=3,cores=1L)


tvAUC(roc.PIN.0)
tvAUC(roc.PIN.1)
tvAUC(roc.PIN.2)
tvAUC(roc.PIN.3)
tvAUC(roc.PIN.4)
tvAUC(roc.PIN.5)
tvAUC(roc.PIN.6)


png("IECV-PIN.png",width = 4200,height =2000,res = 400)
par(mfrow=c(2,4))
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 3,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 4,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 5,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 6,Dt=3,plot = TRUE)
dev.off()


#png("IECV-PIN2.png",width = 4200,height =2000,res = 400)
#par(mfrow=c(2,4))
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 0,Dt=9,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 1,Dt=8,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 2,Dt=7,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 3,Dt=6,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 4,Dt=5,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 5,Dt=4,plot = TRUE)
calibration_plot(jm_dev.PIN,newdata = IECV_vlong_PIN,Tstart = 6,Dt=3,plot = TRUE)
#dev.off()

```

```{r develop model from NYPUM and PINE studies}

IECV_vbase_NP<-data.baseline.fit.up%>%
  filter(study %in% c("NYPUM","PINE"))

IECV_vbase_NP$study<-droplevels(IECV_vbase_NP$study)

IECV_vlong_NP<-data_long.fit.up%>%
  filter(study %in% c("NYPUM","PINE"))

IECV_vlong_NP$study<-droplevels(IECV_vlong_NP$study)

Cox_NP<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl+study,data=IECV_vbase_NP, x = TRUE,model = TRUE)

cox.zph(Cox_NP) #study pass, Global pass


mmse.NP<-lme(mmse~study+agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_NP)

mds.NP<-lme(MDSUPDRS3~study+agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_NP)

Mixed_NP<-list(mmse.NP,mds.NP) 

Cox_NP<-coxph(Surv(years,cens)~study+agebl+sex+hybl+cognitivebl+hallucinationsbl,data=IECV_vbase_NP, x = TRUE,model = TRUE)

cox.zph(Cox_NP) #study is 0.015, but global pass

#jm_dev.NP<-jm(Cox_NP,Mixed_objects = Mixed_NP,time_var = "followupyears")

summary(jm_dev.NP)

```


```{r extre validation only NYPUM and the model only develop with PINE study}

#----PINE dataset-----

IECV_vlong_PIN<-data_long.fit.up.noPIC%>%
  filter(study=="PINE")

IECV_vlong_PIN$study<-droplevels(IECV_vlong_PIN$study)

IECV_vbase_PIN<-data.baseline.fit.up.noPIC%>%
  filter(study=="PINE")

IECV_vbase_PIN$study<-droplevels(IECV_vbase_PIN$study)


mmse.PINE<-lme(mmse~agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_PIN)

mds.PINE<-lme(MDSUPDRS3~agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_PIN)

Mixed_PINE<-list(mmse.PINE,mds.PINE) 

Cox_PINE<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl,data=IECV_vbase_PIN, x = TRUE,model = TRUE)  

#jm_PINE<-jm(Cox_PINE,Mixed_objects = Mixed_PINE,time_var = "followupyears") 

summary(jm_PINE)


#----Validate in NYPUM study----

IECV_vlong_NY<-data_long.fit.up.noPIC%>%
  filter(study=="NYPUM")

IECV_vlong_NY$study<-droplevels(IECV_vlong_NY$study)


roc.ny.0<-tvROC(jm_PINE,newdata=IECV_vlong_NY,Tstart = 0,Dt=3,cores=1L)
roc.ny.1<-tvROC(jm_PINE,newdata=IECV_vlong_NY,Tstart = 1,Dt=3,cores=1L)
roc.ny.2<-tvROC(jm_PINE,newdata=IECV_vlong_NY,Tstart = 2,Dt=3,cores=1L)
roc.ny.3<-tvROC(jm_PINE,newdata=IECV_vlong_NY,Tstart = 3,Dt=3,cores=1L)
roc.ny.4<-tvROC(jm_PINE,newdata=IECV_vlong_NY,Tstart = 4,Dt=3,cores=1L)
roc.ny.5<-tvROC(jm_PINE,newdata=IECV_vlong_NY,Tstart = 5,Dt=3,cores=1L)
roc.ny.6<-tvROC(jm_PINE,newdata=IECV_vlong_NY,Tstart = 6,Dt=3,cores=1L)



tvAUC(roc.ny.0)
tvAUC(roc.ny.1)
tvAUC(roc.ny.2)
tvAUC(roc.ny.3)
tvAUC(roc.ny.4)
tvAUC(roc.ny.5)
tvAUC(roc.ny.6)


png("EV-ny.png",width = 4200,height =2000,res = 400)
par(mfrow=c(2,4))
calibration_plot(jm_PINE,newdata = IECV_vlong_NY,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_PINE,newdata = IECV_vlong_NY,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_PINE,newdata = IECV_vlong_NY,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_PINE,newdata = IECV_vlong_NY,Tstart = 3,Dt=3,plot = TRUE)
calibration_plot(jm_PINE,newdata = IECV_vlong_NY,Tstart = 4,Dt=3,plot = TRUE)
calibration_plot(jm_PINE,newdata = IECV_vlong_NY,Tstart = 5,Dt=3,plot = TRUE)
calibration_plot(jm_PINE,newdata = IECV_vlong_NY,Tstart = 6,Dt=3,plot = TRUE)
dev.off()

```


```{r extre validation only PINE and the model only develop with NYPUM study}

#----NYPUM dataset-----

IECV_vlong_NY<-data_long.fit.up.noPIC%>%
  filter(study=="NYPUM")

IECV_vlong_NY$study<-droplevels(IECV_vlong_NY$study)

IECV_vbase_NY<-data.baseline.fit.up.noPIC%>%
  filter(study=="NYPUM")

IECV_vbase_NY$study<-droplevels(IECV_vbase_NY$study)


mmse.NYPUM<-lme(mmse~agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_NY)

mds.NYPUM<-lme(MDSUPDRS3~agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_NY)

Mixed_NYPUM<-list(mmse.NYPUM,mds.NYPUM) 

Cox_NYPUM<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl,data=IECV_vbase_NY, x = TRUE,model = TRUE)  

#jm_NYPUM<-jm(Cox_NYPUM,Mixed_objects = Mixed_NYPUM,time_var = "followupyears") 

summary(jm_NYPUM)


#----Validate in PINE study----

#IECV_vlong_PIN


roc.pi.0<-tvROC(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 0,Dt=3,cores=1L)
roc.pi.1<-tvROC(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 1,Dt=3,cores=1L)
roc.pi.2<-tvROC(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 2,Dt=3,cores=1L)
roc.pi.3<-tvROC(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 3,Dt=3,cores=1L)
roc.pi.4<-tvROC(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 4,Dt=3,cores=1L)
roc.pi.5<-tvROC(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 5,Dt=3,cores=1L)
roc.pi.6<-tvROC(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 6,Dt=3,cores=1L)



tvAUC(roc.pi.0)
tvAUC(roc.pi.1)
tvAUC(roc.pi.2)
tvAUC(roc.pi.3)
tvAUC(roc.pi.4)
tvAUC(roc.pi.5)
tvAUC(roc.pi.6)


#png("EV-pi.png",width = 4200,height =2000,res = 400)
#par(mfrow=c(2,4))
calibration_plot(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 3,Dt=3,plot = TRUE)
calibration_plot(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 4,Dt=3,plot = TRUE)
calibration_plot(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 5,Dt=3,plot = TRUE)
calibration_plot(jm_NYPUM,newdata=IECV_vlong_PIN,Tstart = 6,Dt=3,plot = TRUE)
#dev.off()

```


```{r develop model from CamPalGN PICNICS ParkWest and did the IECV}

#------develop model from CamPalGN and ParkWest study----

IECV_vbase_CPP<-data.baseline.fit.up%>%
  filter(study %in% c("CamPalGN","ParkWest"))

IECV_vbase_CPP$study<-droplevels(IECV_vbase_CPP$study)

IECV_vlong_CPP<-data_long.fit.up%>%
  filter(study %in% c("CamPalGN","ParkWest"))

IECV_vlong_CPP$study<-droplevels(IECV_vlong_CPP$study)

#Cox_CPP<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl+study,data=IECV_vbase_CPP, x = TRUE,model = TRUE)

#cox.zph(Cox_CPP) #study pass, Global pass


mmse.CPP<-lme(mmse~study+agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_CPP)

mds.CPP<-lme(MDSUPDRS3~study+agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_CPP)

Mixed_CPP<-list(mmse.CPP,mds.CPP) 

Cox_CPP<-coxph(Surv(years,cens)~study+agebl+sex+hybl+cognitivebl+hallucinationsbl,data=IECV_vbase_CPP, x = TRUE,model = TRUE)

#jm_dev.CPP<-jm(Cox_CPP,Mixed_objects = Mixed_CPP,time_var = "followupyears") 

summary(jm_dev.CPP)

#-----validate on PICNICS----

IECV_vlong_PIC<-data_long.fit.up%>%
  filter(study=="PICNICS")

IECV_vlong_PIC$study<-droplevels(IECV_vlong_PIC$study)

levels(IECV_vlong_PIC$study)<-c("ParkWest","CamPalGN")

roc.p.c.0<-tvROC(jm_dev.CPP,newdata=IECV_vlong_PIC,Tstart = 0,Dt=3,cores=1L)
roc.p.c.1<-tvROC(jm_dev.CPP,newdata=IECV_vlong_PIC,Tstart = 1,Dt=3,cores=1L)
roc.p.c.2<-tvROC(jm_dev.CPP,newdata=IECV_vlong_PIC,Tstart = 2,Dt=3,cores=1L)
roc.p.c.3<-tvROC(jm_dev.CPP,newdata=IECV_vlong_PIC,Tstart = 3,Dt=3,cores=1L)
roc.p.c.4<-tvROC(jm_dev.CPP,newdata=IECV_vlong_PIC,Tstart = 4,Dt=3,cores=1L)
roc.p.c.5<-tvROC(jm_dev.CPP,newdata=IECV_vlong_PIC,Tstart = 5,Dt=3,cores=1L)

tvAUC(roc.p.c.0)
tvAUC(roc.p.c.1)
tvAUC(roc.p.c.2)
tvAUC(roc.p.c.3)
tvAUC(roc.p.c.4)
tvAUC(roc.p.c.5)

#------develop model from PICNICS and ParkWest study----

IECV_vbase_CPP2<-data.baseline.fit.up%>%
  filter(study %in% c("PICNICS","ParkWest"))

IECV_vbase_CPP2$study<-droplevels(IECV_vbase_CPP2$study)

IECV_vlong_CPP2<-data_long.fit.up%>%
  filter(study %in% c("PICNICS","ParkWest"))

IECV_vlong_CPP2$study<-droplevels(IECV_vlong_CPP2$study)

mmse.CPP2<-lme(mmse~study+agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_CPP2)

mds.CPP2<-lme(MDSUPDRS3~study+agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_CPP2)

Mixed_CPP2<-list(mmse.CPP2,mds.CPP2) 

Cox_CPP2<-coxph(Surv(years,cens)~study+agebl+sex+hybl+cognitivebl+hallucinationsbl,data=IECV_vbase_CPP2, x = TRUE,model = TRUE)

#jm_dev.CPP2<-jm(Cox_CPP2,Mixed_objects = Mixed_CPP2,time_var = "followupyears") 

summary(jm_dev.CPP2)

#-----validate on CamPalGN----

IECV_vlong_Cam<-data_long.fit.up%>%
  filter(study=="CamPalGN")

IECV_vlong_Cam$study<-droplevels(IECV_vlong_Cam$study)

levels(IECV_vlong_Cam$study)<-c("PICNICS","ParkWest")

roc.c.p.0<-tvROC(jm_dev.CPP2,newdata=IECV_vlong_Cam,Tstart = 0,Dt=3,cores=1L)
roc.c.p.1<-tvROC(jm_dev.CPP2,newdata=IECV_vlong_Cam,Tstart = 1,Dt=3,cores=1L)
roc.c.p.2<-tvROC(jm_dev.CPP2,newdata=IECV_vlong_Cam,Tstart = 2,Dt=3,cores=1L)
roc.c.p.3<-tvROC(jm_dev.CPP2,newdata=IECV_vlong_Cam,Tstart = 3,Dt=3,cores=1L)
roc.c.p.4<-tvROC(jm_dev.CPP2,newdata=IECV_vlong_Cam,Tstart = 4,Dt=3,cores=1L)
roc.c.p.5<-tvROC(jm_dev.CPP2,newdata=IECV_vlong_Cam,Tstart = 5,Dt=3,cores=1L)

tvAUC(roc.c.p.0)
tvAUC(roc.c.p.1)
tvAUC(roc.c.p.2)
tvAUC(roc.c.p.3)
tvAUC(roc.c.p.4)
tvAUC(roc.c.p.5)

#------develop model from CamPalGN and PICNICS study----

IECV_vbase_CPP3<-data.baseline.fit.up%>%
  filter(study %in% c("CamPalGN","PICNICS"))

IECV_vbase_CPP3$study<-droplevels(IECV_vbase_CPP3$study)

IECV_vlong_CPP3<-data_long.fit.up%>%
  filter(study %in% c("CamPalGN","PICNICS"))

IECV_vlong_CPP3$study<-droplevels(IECV_vlong_CPP3$study)

mmse.CPP3<-lme(mmse~study+agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_CPP3)

#The linear mixed model mmse, has covergence problem,even change to just follow-up year still has this problem

mds.CPP3<-lme(MDSUPDRS3~study+agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_CPP3)

Mixed_CPP3<-list(mmse.CPP3,mds.CPP3) 

Cox_CPP3<-coxph(Surv(years,cens)~study+agebl+sex+hybl+cognitivebl+hallucinationsbl,data=IECV_vbase_CPP3, x = TRUE,model = TRUE)

jm_dev.CPP3<-jm(Cox_CPP3,Mixed_objects = Mixed_CPP3,time_var = "followupyears") 

summary(jm_dev.CPP3)

#-----validate on ParkWest----

IECV_vlong_PA<-data_long.fit.up%>%
  filter(study=="ParkWest")

IECV_vlong_PA$study<-droplevels(IECV_vlong_PA$study)

levels(IECV_vlong_PA$study)<-c("PICNICS","CamPalGN")

roc.p.p.0<-tvROC(jm_dev.CPP3,newdata=IECV_vlong_PA,Tstart = 0,Dt=3,cores=1L)
roc.p.p.1<-tvROC(jm_dev.CPP3,newdata=IECV_vlong_PA,Tstart = 1,Dt=3,cores=1L)
roc.p.p.2<-tvROC(jm_dev.CPP3,newdata=IECV_vlong_PA,Tstart = 2,Dt=3,cores=1L)
roc.p.p.3<-tvROC(jm_dev.CPP3,newdata=IECV_vlong_PA,Tstart = 3,Dt=3,cores=1L)
roc.p.p.4<-tvROC(jm_dev.CPP3,newdata=IECV_vlong_PA,Tstart = 4,Dt=3,cores=1L)
roc.p.p.5<-tvROC(jm_dev.CPP3,newdata=IECV_vlong_PA,Tstart = 5,Dt=3,cores=1L)

tvAUC(roc.p.p.0)
tvAUC(roc.p.p.1)
tvAUC(roc.p.p.2)
tvAUC(roc.p.p.3)
tvAUC(roc.p.p.4)
tvAUC(roc.p.p.5)

```


```{r IECV model from ParkWest and CamPalGN and validation in CamPalGN}

#So the model developement from PICNICS and ParkWest and validate in CamPalGN is bad

#Now I tried to develop the model from ParkWest and validate in CamPalGN to see how it goes

IECV_vbase_PP<-data.baseline.fit.up%>%
  filter(study %in% c("ParkWest"))

IECV_vbase_PP$study<-droplevels(IECV_vbase_PP$study)

IECV_vlong_PP<-data_long.fit.up%>%
  filter(study %in% c("ParkWest"))

IECV_vlong_PP$study<-droplevels(IECV_vlong_PP$study)

#levels(IECV_vbase_PP$study)

mmse.PP<-lme(mmse~agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_PP)

mds.PP<-lme(MDSUPDRS3~agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_PP)

Mixed_PP<-list(mmse.PP,mds.PP) 

Cox_PP<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl,data=IECV_vbase_PP, x = TRUE,model = TRUE)
#cox.zph(Cox_PP) all pass

#jm_dev.PP<-jm(Cox_PP,Mixed_objects = Mixed_PP,time_var = "followupyears") 

summary(jm_dev.PP)

#-----validate in CamPalGN----

#IECV_vlong_Cam<-data_long.fit.up.noPIC%>%
#  filter(study=="CamPalGN")

#IECV_vlong_Cam$study<-droplevels(IECV_vlong_Cam$study)

#levels(IECV_vlong_Cam$study)<-c("PICNICS","ParkWest") #Only take NYPUM levels, other levels won't be used

roc.Cam.CPP.0<-tvROC(jm_dev.PP,newdata=IECV_vlong_Cam,Tstart = 0,Dt=3,cores=1L)
roc.Cam.CPP.1<-tvROC(jm_dev.PP,newdata=IECV_vlong_Cam,Tstart = 1,Dt=3,cores=1L)
roc.Cam.CPP.2<-tvROC(jm_dev.PP,newdata=IECV_vlong_Cam,Tstart = 2,Dt=3,cores=1L)
roc.Cam.CPP.3<-tvROC(jm_dev.PP,newdata=IECV_vlong_Cam,Tstart = 3,Dt=3,cores=1L)
roc.Cam.CPP.4<-tvROC(jm_dev.PP,newdata=IECV_vlong_Cam,Tstart = 4,Dt=3,cores=1L)



tvAUC(roc.Cam.CPP.0)
tvAUC(roc.Cam.CPP.1)
tvAUC(roc.Cam.CPP.2)
tvAUC(roc.Cam.CPP.3)
tvAUC(roc.Cam.CPP.4)



png("IECV-Cam.PP.png",width = 3000,height =2000,res = 400)
par(mfrow=c(2,3))
calibration_plot(jm_dev.PP,newdata = IECV_vlong_Cam,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PP,newdata = IECV_vlong_Cam,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PP,newdata = IECV_vlong_Cam,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PP,newdata = IECV_vlong_Cam,Tstart = 3,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PP,newdata = IECV_vlong_Cam,Tstart = 4,Dt=3,plot = TRUE)
dev.off()

```


```{r IECV model from ParkWest and CamPalGN, validation in ParkWest}

IECV_vbase_Cam<-data.baseline.fit.up%>%
  filter(study %in% c("CamPalGN"))

IECV_vbase_Cam$study<-droplevels(IECV_vbase_Cam$study)

IECV_vlong_Cam<-data_long.fit.up%>%
  filter(study %in% c("CamPalGN"))

IECV_vlong_Cam$study<-droplevels(IECV_vlong_Cam$study)

#levels(IECV_vbase_Cam$study)

mmse.Cam<-lme(mmse~agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_Cam)

mds.Cam<-lme(MDSUPDRS3~agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_Cam)

Mixed_Cam<-list(mmse.Cam,mds.Cam) 

Cox_Cam<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl,data=IECV_vbase_Cam, x = TRUE,model = TRUE)
#cox.zph(Cox_Cam) all pass

#jm_dev.Cam<-jm(Cox_Cam,Mixed_objects = Mixed_Cam,time_var = "followupyears") 

summary(jm_dev.Cam)

#-----validate in ParkWest----

IECV_vlong_PA<-data_long.fit.up.noPIC%>%
  filter(study=="ParkWest")

IECV_vlong_PA$study<-droplevels(IECV_vlong_PA$study)

roc.pa.0<-tvROC(jm_dev.Cam,newdata=IECV_vlong_PA,Tstart = 0,Dt=3,cores=1L)
roc.pa.1<-tvROC(jm_dev.Cam,newdata=IECV_vlong_PA,Tstart = 1,Dt=3,cores=1L)
roc.pa.2<-tvROC(jm_dev.Cam,newdata=IECV_vlong_PA,Tstart = 2,Dt=3,cores=1L)
roc.pa.3<-tvROC(jm_dev.Cam,newdata=IECV_vlong_PA,Tstart = 3,Dt=3,cores=1L)
roc.pa.4<-tvROC(jm_dev.Cam,newdata=IECV_vlong_PA,Tstart = 4,Dt=3,cores=1L)



tvAUC(roc.pa.0)
tvAUC(roc.pa.1)
tvAUC(roc.pa.2)
tvAUC(roc.pa.3)
tvAUC(roc.pa.4)


png("EV-pa.png",width = 3000,height =2000,res = 400)
par(mfrow=c(2,3))
calibration_plot(jm_dev.Cam,newdata=IECV_vlong_PA,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_dev.Cam,newdata=IECV_vlong_PA,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_dev.Cam,newdata=IECV_vlong_PA,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_dev.Cam,newdata=IECV_vlong_PA,Tstart = 3,Dt=3,plot = TRUE)
calibration_plot(jm_dev.Cam,newdata=IECV_vlong_PA,Tstart = 4,Dt=3,plot = TRUE)
dev.off()

```

```{r summary above}

#The model development from NYPUM and PINE is good, both in NYPUM and PINE

#The model development from CamPalGN, PICNICS, ParkWest are bad, and cannot perform IECV on ParkWest as the data of CamPalGN and PICNICS the mmse is not convergence

#The model development from CamPalGN and ParkWest, only good in CamPalGN

#I am now try develop model just for PICNICS and ParkWest

#---model just develop from ParkWest---

summary(jm_dev.PP)

#-----validate in PICNICS----

IECV_vlong_PIC<-data_long.fit.up%>%
  filter(study=="PICNICS")

IECV_vlong_PIC$study<-droplevels(IECV_vlong_PIC$study)

roc.pic.0<-tvROC(jm_dev.PP,newdata=IECV_vlong_PIC,Tstart = 0,Dt=3,cores=1L)
roc.pic.1<-tvROC(jm_dev.PP,newdata=IECV_vlong_PIC,Tstart = 1,Dt=3,cores=1L)
roc.pic.2<-tvROC(jm_dev.PP,newdata=IECV_vlong_PIC,Tstart = 2,Dt=3,cores=1L)
roc.pic.3<-tvROC(jm_dev.PP,newdata=IECV_vlong_PIC,Tstart = 3,Dt=3,cores=1L)
roc.pic.4<-tvROC(jm_dev.PP,newdata=IECV_vlong_PIC,Tstart = 4,Dt=3,cores=1L)



tvAUC(roc.pic.0)
tvAUC(roc.pic.1)
tvAUC(roc.pic.2)
tvAUC(roc.pic.3)
tvAUC(roc.pic.4)


png("IECV-PIC.PP.png",width = 3000,height =2000,res = 400)
par(mfrow=c(2,3))
calibration_plot(jm_dev.PP,newdata = IECV_vlong_PIC,Tstart = 0,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PP,newdata = IECV_vlong_PIC,Tstart = 1,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PP,newdata = IECV_vlong_PIC,Tstart = 2,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PP,newdata = IECV_vlong_PIC,Tstart = 3,Dt=3,plot = TRUE)
calibration_plot(jm_dev.PP,newdata = IECV_vlong_PIC,Tstart = 4,Dt=3,plot = TRUE)
dev.off()

```

```{r model development on PICNICS and validate on ParkWest}

#I am now only develop model for PICNICS

IECV_vlong_PIC<-data_long.fit.up%>%
  filter(study=="PICNICS")

IECV_vlong_PIC$study<-droplevels(IECV_vlong_PIC$study)

IECV_vbase_PIC<-data.baseline.fit.up%>%
  filter(study %in% c("PICNICS"))

IECV_vbase_PIC$study<-droplevels(IECV_vbase_PIC$study)

mmse.PIC<-lme(mmse~agebl+sex+yearseducation+cognitivebl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_PIC)

mds.PIC<-lme(MDSUPDRS3~agebl+sex+hybl+rcs(followupyears,3), random = ~ followupyears | idpicc, data=IECV_vlong_PIC)

Mixed_PIC<-list(mmse.PIC,mds.PIC) 

Cox_PIC<-coxph(Surv(years,cens)~agebl+sex+hybl+cognitivebl+hallucinationsbl,data=IECV_vbase_PIC, x = TRUE,model = TRUE)

#jm_dev.PIC<-jm(Cox_PIC,Mixed_objects = Mixed_PIC,time_var = "followupyears") 

summary(jm_dev.PIC)


#-----validate in ParkWest----


roc.pa.p.0<-tvROC(jm_dev.PIC,newdata=IECV_vlong_PA,Tstart = 0,Dt=3,cores=1L)
roc.pa.p.1<-tvROC(jm_dev.PIC,newdata=IECV_vlong_PA,Tstart = 1,Dt=3,cores=1L)
roc.pa.p.2<-tvROC(jm_dev.PIC,newdata=IECV_vlong_PA,Tstart = 2,Dt=3,cores=1L)
roc.pa.p.3<-tvROC(jm_dev.PIC,newdata=IECV_vlong_PA,Tstart = 3,Dt=3,cores=1L)
roc.pa.p.4<-tvROC(jm_dev.PIC,newdata=IECV_vlong_PA,Tstart = 4,Dt=3,cores=1L)



tvAUC(roc.pa.p.0)
tvAUC(roc.pa.p.1)
tvAUC(roc.pa.p.2)
tvAUC(roc.pa.p.3)
tvAUC(roc.pa.p.4)

```

```{r model developement from CamPalGN and PICNICS AND IECV on them}

#----Validate in CamPalGN---

roc.Cam.PIC.0<-tvROC(jm_dev.PIC,newdata=IECV_vlong_Cam,Tstart = 0,Dt=3,cores=1L)
roc.Cam.PIC.1<-tvROC(jm_dev.PIC,newdata=IECV_vlong_Cam,Tstart = 1,Dt=3,cores=1L)
roc.Cam.PIC.2<-tvROC(jm_dev.PIC,newdata=IECV_vlong_Cam,Tstart = 2,Dt=3,cores=1L)
roc.Cam.PIC.3<-tvROC(jm_dev.PIC,newdata=IECV_vlong_Cam,Tstart = 3,Dt=3,cores=1L)
roc.Cam.PIC.4<-tvROC(jm_dev.PIC,newdata=IECV_vlong_Cam,Tstart = 4,Dt=3,cores=1L)



tvAUC(roc.Cam.PIC.0)
tvAUC(roc.Cam.PIC.1)
tvAUC(roc.Cam.PIC.2)
tvAUC(roc.Cam.PIC.3)
tvAUC(roc.Cam.PIC.4)

#----Validate in PICNICS---

roc.pic.c.0<-tvROC(jm_dev.Cam,newdata=IECV_vlong_PIC,Tstart = 0,Dt=3,cores=1L)
roc.pic.c.1<-tvROC(jm_dev.Cam,newdata=IECV_vlong_PIC,Tstart = 1,Dt=3,cores=1L)
roc.pic.c.2<-tvROC(jm_dev.Cam,newdata=IECV_vlong_PIC,Tstart = 2,Dt=3,cores=1L)
roc.pic.c.3<-tvROC(jm_dev.Cam,newdata=IECV_vlong_PIC,Tstart = 3,Dt=3,cores=1L)
roc.pic.c.4<-tvROC(jm_dev.Cam,newdata=IECV_vlong_PIC,Tstart = 4,Dt=3,cores=1L)



tvAUC(roc.pic.c.0)
tvAUC(roc.pic.c.1)
tvAUC(roc.pic.c.2)
tvAUC(roc.pic.c.3)
tvAUC(roc.pic.c.4)

```


```{r predict individal in NYPUM}

#JM model is jm_dev.NP

IECV_vlong_NY%>%
  filter(cens==1)

#random select idpicc==305

predict.data<-IECV_vlong_NY[IECV_vlong_NY$idpicc == 308,] #event at 8.5 years

levels(predict.data$study)<-c("NYPUM","PINE") #it will only take NYPUM level

#----Only baseline information-----

predict.data.time.0<-predict.data[predict.data$followupyears==0,] 

predict.data.time.0$cens<-0 #not event

predict.data.time.0$years<-0 #predict time at 0 years

predMMSE.0<-predict(jm_dev.NP,newdata = predict.data.time.0,times = seq(0,3, length.out=20),return_newdata = T) #for future time point

predSurv.0<-predict(jm_dev.NP,newdata = predict.data.time.0,process = "event",times = seq(0,3, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.0,predSurv.0)

#-----From baseline up to 1 year-----

predict.data.time.1<-predict.data[predict.data$followupyears<1.1,] 

predict.data.time.1$cens<-0 #not event

predict.data.time.1$years<-1.1 

predMMSE.1<-predict(jm_dev.NP,newdata = predict.data.time.1,times = seq(1.1,4, length.out=20),return_newdata = T) #for future time point

predSurv.1<-predict(jm_dev.NP,newdata = predict.data.time.1,process = "event",times = seq(1.1,4, length.out=20),return_newdata = T) # use the information before 3 years to predict


plot(predMMSE.1,predSurv.1)

#-----From baseline up to 2 year-----

predict.data.time.2<-predict.data[predict.data$followupyears<2,] 

predict.data.time.2$cens<-0 #not event

predict.data.time.2$years<-2

predMMSE.2<-predict(jm_dev.NP,newdata = predict.data.time.2,times = seq(2,5, length.out=20),return_newdata = T) #for future time point

predSurv.2<-predict(jm_dev.NP,newdata = predict.data.time.2,process = "event",times = seq(2,5, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.2,predSurv.2)

#------From baseline up to 3 years-----

predict.data.time.3<-predict.data[predict.data$followupyears<4,] 

predict.data.time.3$cens<-0 #not event

predict.data.time.3$years<-3.05 

#predict for longitudinal outcomes

predMMSE.3<-predict(jm_dev.NP,newdata = predict.data.time.3,times = seq(3.05,6, length.out=20),return_newdata = T) #for future time point

predSurv.3<-predict(jm_dev.NP,newdata = predict.data.time.3,process = "event",times = seq(3.05,6, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.3,predSurv.3)

#------From baseline up to 4 years-----

predict.data.time.4<-predict.data[predict.data$followupyears<5,] 

predict.data.time.4$cens<-0 #not event

predict.data.time.4$years<-4.05 

#predict for longitudinal outcomes

predMMSE.4<-predict(jm_dev.NP,newdata = predict.data.time.4,times = seq(4.05,7, length.out=20),return_newdata = T) #for future time point

predSurv.4<-predict(jm_dev.NP,newdata = predict.data.time.4,process = "event",times = seq(4.05,7, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.4,predSurv.4)

#------From baseline up to 5 years-----

predict.data.time.5<-predict.data[predict.data$followupyears<6,] 

predict.data.time.5$cens<-0 #not event

predict.data.time.5$years<-5.06 

#predict for longitudinal outcomes

predMMSE.5<-predict(jm_dev.NP,newdata = predict.data.time.5,times = seq(5.06,8, length.out=20),return_newdata = T) #for future time point

predSurv.5<-predict(jm_dev.NP,newdata = predict.data.time.5,process = "event",times = seq(5.06,8, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.5,predSurv.5)

#------From baseline up to 7 years-----

predict.data.time.7<-predict.data[predict.data$followupyears<8,] 

predict.data.time.7$cens<-0 #not event

predict.data.time.7$years<-7.06

#predict for longitudinal outcomes

predMMSE.7<-predict(jm_dev.NP,newdata = predict.data.time.7,times = seq(7.06,10, length.out=20),return_newdata = T) #for future time point

predSurv.7<-predict(jm_dev.NP,newdata = predict.data.time.7,process = "event",times = seq(7.06,10, length.out=20),return_newdata = T) # use the information before 3 years to predict

plot(predMMSE.7,predSurv.7)





```
